//
//  Licensed to the Apache Software Foundation (ASF) under one or more
//  contributor license agreements.  See the NOTICE file distributed with
//  this work for additional information regarding copyright ownership.
//  The ASF licenses this file to You under the Apache License, Version 2.0
//  (the "License"); you may not use this file except in compliance with
//  the License.  You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

== Mac OS

Most libraries on Mac are installed using `Homebrew`.

Make sure `Homebrew` ist installed in order to install most of these.

    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

=== Git

Checking:

 git --version

If you get any successful output, you probably don't need to do anything.

In order to install it, please execute the following command:

 brew install git

=== LibPCAP

The libpcap version bundled with Mac OS is currently 1.9.1.
This version causes exceptions.
So it's best to update to a newer version using brew:

   brew install libpcap

=== gcc

Checking:

 gcc --version

If you get any successful output, you probably don't need to do anything.

It seems macOS comes with a version of gcc which is good enough for our usecases.

=== dotnet

Checking:

 dotnet --version

If you get any successful output, you probably don't need to do anything.

Microsoft is offering an installer for MacOS which is available from https://dotnet.microsoft.com/download/dotnet-core/2.2[here].

Alternatively you can also install it via homebrew:

 brew install --cask dotnet-sdk

=== python

Checking:

 python --version

If you get a version of 3.0.0 or higher reported, you probably don't need to do anything.

In order to install it, please execute the following command:

 brew install pyenv

Then use pyenv to install python:

 pyenv install 3.9.13

Then set this as the global python version:

 pyenv global 3.9.13

And add pyenv to the PATH:

 echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n  eval "$(pyenv init -)"\nfi' >> ~/.zshrc
 $ echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n  eval "$(pyenv init -)"\nfi' >> ~/.bash_profile

After opening a new terminal, `python` should be configured

 python --version
