//
//  Licensed to the Apache Software Foundation (ASF) under one or more
//  contributor license agreements.  See the NOTICE file distributed with
//  this work for additional information regarding copyright ownership.
//  The ASF licenses this file to You under the Apache License, Version 2.0
//  (the "License"); you may not use this file except in compliance with
//  the License.  You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
:imagesdir: ../../images/users/protocols
:icons: font

= Logix



== Connection String Options

include::partial$logix.adoc[]

== Individual Resource Address Format

=== Connection String

Logix has the following connection string format:-
----
logix:tcp://{ip-address}:{port}?{options}
----
An example connection string would look like:-
----
logix:tcp://127.0.0.1:44818?communication-path=[1,1]
----
Note the port and option fields are optional.


=== General Format

In general all Logix addresses have this format:

----
{tagname}
{tagname}:{DataType}
{tagname}:{numberOfElements}
{tagname}[{startIndex}]:{DataType}:{numberOfElements}
----

The tag name matches that found in the controller and may optionally be prefixed with `%`.
An array index is appended to the tag name and has to be its last part.

If the number-of-elements part is omitted, `1` is assumed.
If the data type is omitted it defaults to `DINT`, so for anything that is not a 32-bit integer it
has to be given explicitly - also when reading.

NOTE: The data type comes *before* the number of elements. Reading four DINTs starting at index 0
is `myArray[0]:DINT:4`.

=== Data Types

The following data types are supported

- BOOL (boolean)
- SINT (int 8)
- INT (int 16)
- DINT (int 32)
- LINT (int 64)
- REAL (float)
- LREAL (double)
- STRING (character string)

NOTE: Other CIP data types are accepted by the address parser but are not encoded or decoded by the
driver; reading such a tag results in a response code of `INTERNAL_ERROR` rather than a value.