/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package model

import (
	"github.com/apache/plc4x/plc4go/internal/plc4go/spi/utils"
	"github.com/pkg/errors"
)

// Code generated by code-generation. DO NOT EDIT.

// The data-structure of this message
type BACnetTagPayloadUnsignedInteger struct {
	ValueUint8  *uint8
	ValueUint16 *uint16
	ValueUint24 *uint32
	ValueUint32 *uint32
	ValueUint40 *uint64
	ValueUint48 *uint64
	ValueUint56 *uint64
	ValueUint64 *uint64

	// Arguments.
	ActualLength uint32
}

// The corresponding interface
type IBACnetTagPayloadUnsignedInteger interface {
	// GetValueUint8 returns ValueUint8
	GetValueUint8() *uint8
	// GetValueUint16 returns ValueUint16
	GetValueUint16() *uint16
	// GetValueUint24 returns ValueUint24
	GetValueUint24() *uint32
	// GetValueUint32 returns ValueUint32
	GetValueUint32() *uint32
	// GetValueUint40 returns ValueUint40
	GetValueUint40() *uint64
	// GetValueUint48 returns ValueUint48
	GetValueUint48() *uint64
	// GetValueUint56 returns ValueUint56
	GetValueUint56() *uint64
	// GetValueUint64 returns ValueUint64
	GetValueUint64() *uint64
	// GetIsUint8 returns IsUint8
	GetIsUint8() bool
	// GetIsUint16 returns IsUint16
	GetIsUint16() bool
	// GetIsUint24 returns IsUint24
	GetIsUint24() bool
	// GetIsUint32 returns IsUint32
	GetIsUint32() bool
	// GetIsUint40 returns IsUint40
	GetIsUint40() bool
	// GetIsUint48 returns IsUint48
	GetIsUint48() bool
	// GetIsUint56 returns IsUint56
	GetIsUint56() bool
	// GetIsUint64 returns IsUint64
	GetIsUint64() bool
	// GetActualValue returns ActualValue
	GetActualValue() uint64
	// GetLengthInBytes returns the length in bytes
	GetLengthInBytes() uint16
	// GetLengthInBits returns the length in bits
	GetLengthInBits() uint16
	// Serialize serializes this type
	Serialize(writeBuffer utils.WriteBuffer) error
}

///////////////////////////////////////////////////////////
// Accessors for property fields.
///////////////////////////////////////////////////////////
func (m *BACnetTagPayloadUnsignedInteger) GetValueUint8() *uint8 {
	return m.ValueUint8
}

func (m *BACnetTagPayloadUnsignedInteger) GetValueUint16() *uint16 {
	return m.ValueUint16
}

func (m *BACnetTagPayloadUnsignedInteger) GetValueUint24() *uint32 {
	return m.ValueUint24
}

func (m *BACnetTagPayloadUnsignedInteger) GetValueUint32() *uint32 {
	return m.ValueUint32
}

func (m *BACnetTagPayloadUnsignedInteger) GetValueUint40() *uint64 {
	return m.ValueUint40
}

func (m *BACnetTagPayloadUnsignedInteger) GetValueUint48() *uint64 {
	return m.ValueUint48
}

func (m *BACnetTagPayloadUnsignedInteger) GetValueUint56() *uint64 {
	return m.ValueUint56
}

func (m *BACnetTagPayloadUnsignedInteger) GetValueUint64() *uint64 {
	return m.ValueUint64
}

///////////////////////////////////////////////////////////
// Accessors for virtual fields.
///////////////////////////////////////////////////////////
func (m *BACnetTagPayloadUnsignedInteger) GetIsUint8() bool {
	valueUint8 := m.ValueUint8
	_ = valueUint8
	valueUint16 := m.ValueUint16
	_ = valueUint16
	valueUint24 := m.ValueUint24
	_ = valueUint24
	valueUint32 := m.ValueUint32
	_ = valueUint32
	valueUint40 := m.ValueUint40
	_ = valueUint40
	valueUint48 := m.ValueUint48
	_ = valueUint48
	valueUint56 := m.ValueUint56
	_ = valueUint56
	valueUint64 := m.ValueUint64
	_ = valueUint64
	return bool((m.ActualLength) == (1))
}

func (m *BACnetTagPayloadUnsignedInteger) GetIsUint16() bool {
	valueUint8 := m.ValueUint8
	_ = valueUint8
	valueUint16 := m.ValueUint16
	_ = valueUint16
	valueUint24 := m.ValueUint24
	_ = valueUint24
	valueUint32 := m.ValueUint32
	_ = valueUint32
	valueUint40 := m.ValueUint40
	_ = valueUint40
	valueUint48 := m.ValueUint48
	_ = valueUint48
	valueUint56 := m.ValueUint56
	_ = valueUint56
	valueUint64 := m.ValueUint64
	_ = valueUint64
	return bool((m.ActualLength) == (2))
}

func (m *BACnetTagPayloadUnsignedInteger) GetIsUint24() bool {
	valueUint8 := m.ValueUint8
	_ = valueUint8
	valueUint16 := m.ValueUint16
	_ = valueUint16
	valueUint24 := m.ValueUint24
	_ = valueUint24
	valueUint32 := m.ValueUint32
	_ = valueUint32
	valueUint40 := m.ValueUint40
	_ = valueUint40
	valueUint48 := m.ValueUint48
	_ = valueUint48
	valueUint56 := m.ValueUint56
	_ = valueUint56
	valueUint64 := m.ValueUint64
	_ = valueUint64
	return bool((m.ActualLength) == (3))
}

func (m *BACnetTagPayloadUnsignedInteger) GetIsUint32() bool {
	valueUint8 := m.ValueUint8
	_ = valueUint8
	valueUint16 := m.ValueUint16
	_ = valueUint16
	valueUint24 := m.ValueUint24
	_ = valueUint24
	valueUint32 := m.ValueUint32
	_ = valueUint32
	valueUint40 := m.ValueUint40
	_ = valueUint40
	valueUint48 := m.ValueUint48
	_ = valueUint48
	valueUint56 := m.ValueUint56
	_ = valueUint56
	valueUint64 := m.ValueUint64
	_ = valueUint64
	return bool((m.ActualLength) == (4))
}

func (m *BACnetTagPayloadUnsignedInteger) GetIsUint40() bool {
	valueUint8 := m.ValueUint8
	_ = valueUint8
	valueUint16 := m.ValueUint16
	_ = valueUint16
	valueUint24 := m.ValueUint24
	_ = valueUint24
	valueUint32 := m.ValueUint32
	_ = valueUint32
	valueUint40 := m.ValueUint40
	_ = valueUint40
	valueUint48 := m.ValueUint48
	_ = valueUint48
	valueUint56 := m.ValueUint56
	_ = valueUint56
	valueUint64 := m.ValueUint64
	_ = valueUint64
	return bool((m.ActualLength) == (5))
}

func (m *BACnetTagPayloadUnsignedInteger) GetIsUint48() bool {
	valueUint8 := m.ValueUint8
	_ = valueUint8
	valueUint16 := m.ValueUint16
	_ = valueUint16
	valueUint24 := m.ValueUint24
	_ = valueUint24
	valueUint32 := m.ValueUint32
	_ = valueUint32
	valueUint40 := m.ValueUint40
	_ = valueUint40
	valueUint48 := m.ValueUint48
	_ = valueUint48
	valueUint56 := m.ValueUint56
	_ = valueUint56
	valueUint64 := m.ValueUint64
	_ = valueUint64
	return bool((m.ActualLength) == (6))
}

func (m *BACnetTagPayloadUnsignedInteger) GetIsUint56() bool {
	valueUint8 := m.ValueUint8
	_ = valueUint8
	valueUint16 := m.ValueUint16
	_ = valueUint16
	valueUint24 := m.ValueUint24
	_ = valueUint24
	valueUint32 := m.ValueUint32
	_ = valueUint32
	valueUint40 := m.ValueUint40
	_ = valueUint40
	valueUint48 := m.ValueUint48
	_ = valueUint48
	valueUint56 := m.ValueUint56
	_ = valueUint56
	valueUint64 := m.ValueUint64
	_ = valueUint64
	return bool((m.ActualLength) == (7))
}

func (m *BACnetTagPayloadUnsignedInteger) GetIsUint64() bool {
	valueUint8 := m.ValueUint8
	_ = valueUint8
	valueUint16 := m.ValueUint16
	_ = valueUint16
	valueUint24 := m.ValueUint24
	_ = valueUint24
	valueUint32 := m.ValueUint32
	_ = valueUint32
	valueUint40 := m.ValueUint40
	_ = valueUint40
	valueUint48 := m.ValueUint48
	_ = valueUint48
	valueUint56 := m.ValueUint56
	_ = valueUint56
	valueUint64 := m.ValueUint64
	_ = valueUint64
	return bool((m.ActualLength) == (8))
}

func (m *BACnetTagPayloadUnsignedInteger) GetActualValue() uint64 {
	valueUint8 := m.ValueUint8
	_ = valueUint8
	valueUint16 := m.ValueUint16
	_ = valueUint16
	valueUint24 := m.ValueUint24
	_ = valueUint24
	valueUint32 := m.ValueUint32
	_ = valueUint32
	valueUint40 := m.ValueUint40
	_ = valueUint40
	valueUint48 := m.ValueUint48
	_ = valueUint48
	valueUint56 := m.ValueUint56
	_ = valueUint56
	valueUint64 := m.ValueUint64
	_ = valueUint64
	return utils.InlineIf(m.GetIsUint8(), func() interface{} { return uint64((*m.GetValueUint8())) }, func() interface{} {
		return uint64(uint64(utils.InlineIf(m.GetIsUint16(), func() interface{} { return uint64((*m.GetValueUint16())) }, func() interface{} {
			return uint64(uint64(utils.InlineIf(m.GetIsUint24(), func() interface{} { return uint64((*m.GetValueUint24())) }, func() interface{} {
				return uint64(uint64(utils.InlineIf(m.GetIsUint32(), func() interface{} { return uint64((*m.GetValueUint32())) }, func() interface{} {
					return uint64(uint64(utils.InlineIf(m.GetIsUint40(), func() interface{} { return uint64((*m.GetValueUint40())) }, func() interface{} {
						return uint64(uint64(utils.InlineIf(m.GetIsUint48(), func() interface{} { return uint64((*m.GetValueUint48())) }, func() interface{} {
							return uint64(uint64(utils.InlineIf(m.GetIsUint56(), func() interface{} { return uint64((*m.GetValueUint56())) }, func() interface{} { return uint64((*m.GetValueUint64())) }).(uint64)))
						}).(uint64)))
					}).(uint64)))
				}).(uint64)))
			}).(uint64)))
		}).(uint64)))
	}).(uint64)
}

// NewBACnetTagPayloadUnsignedInteger factory function for BACnetTagPayloadUnsignedInteger
func NewBACnetTagPayloadUnsignedInteger(valueUint8 *uint8, valueUint16 *uint16, valueUint24 *uint32, valueUint32 *uint32, valueUint40 *uint64, valueUint48 *uint64, valueUint56 *uint64, valueUint64 *uint64, actualLength uint32) *BACnetTagPayloadUnsignedInteger {
	return &BACnetTagPayloadUnsignedInteger{ValueUint8: valueUint8, ValueUint16: valueUint16, ValueUint24: valueUint24, ValueUint32: valueUint32, ValueUint40: valueUint40, ValueUint48: valueUint48, ValueUint56: valueUint56, ValueUint64: valueUint64, ActualLength: actualLength}
}

func CastBACnetTagPayloadUnsignedInteger(structType interface{}) *BACnetTagPayloadUnsignedInteger {
	castFunc := func(typ interface{}) *BACnetTagPayloadUnsignedInteger {
		if casted, ok := typ.(BACnetTagPayloadUnsignedInteger); ok {
			return &casted
		}
		if casted, ok := typ.(*BACnetTagPayloadUnsignedInteger); ok {
			return casted
		}
		return nil
	}
	return castFunc(structType)
}

func (m *BACnetTagPayloadUnsignedInteger) GetTypeName() string {
	return "BACnetTagPayloadUnsignedInteger"
}

func (m *BACnetTagPayloadUnsignedInteger) GetLengthInBits() uint16 {
	return m.GetLengthInBitsConditional(false)
}

func (m *BACnetTagPayloadUnsignedInteger) GetLengthInBitsConditional(lastItem bool) uint16 {
	lengthInBits := uint16(0)

	// A virtual field doesn't have any in- or output.

	// Optional Field (valueUint8)
	if m.ValueUint8 != nil {
		lengthInBits += 8
	}

	// A virtual field doesn't have any in- or output.

	// Optional Field (valueUint16)
	if m.ValueUint16 != nil {
		lengthInBits += 16
	}

	// A virtual field doesn't have any in- or output.

	// Optional Field (valueUint24)
	if m.ValueUint24 != nil {
		lengthInBits += 24
	}

	// A virtual field doesn't have any in- or output.

	// Optional Field (valueUint32)
	if m.ValueUint32 != nil {
		lengthInBits += 32
	}

	// A virtual field doesn't have any in- or output.

	// Optional Field (valueUint40)
	if m.ValueUint40 != nil {
		lengthInBits += 40
	}

	// A virtual field doesn't have any in- or output.

	// Optional Field (valueUint48)
	if m.ValueUint48 != nil {
		lengthInBits += 48
	}

	// A virtual field doesn't have any in- or output.

	// Optional Field (valueUint56)
	if m.ValueUint56 != nil {
		lengthInBits += 56
	}

	// A virtual field doesn't have any in- or output.

	// Optional Field (valueUint64)
	if m.ValueUint64 != nil {
		lengthInBits += 64
	}

	// A virtual field doesn't have any in- or output.

	return lengthInBits
}

func (m *BACnetTagPayloadUnsignedInteger) GetLengthInBytes() uint16 {
	return m.GetLengthInBits() / 8
}

func BACnetTagPayloadUnsignedIntegerParse(readBuffer utils.ReadBuffer, actualLength uint32) (*BACnetTagPayloadUnsignedInteger, error) {
	if pullErr := readBuffer.PullContext("BACnetTagPayloadUnsignedInteger"); pullErr != nil {
		return nil, pullErr
	}
	currentPos := readBuffer.GetPos()
	_ = currentPos

	// Virtual field
	_isUint8 := bool((actualLength) == (1))
	isUint8 := bool(_isUint8)
	_ = isUint8

	// Optional Field (valueUint8) (Can be skipped, if a given expression evaluates to false)
	var valueUint8 *uint8 = nil
	if isUint8 {
		_val, _err := readBuffer.ReadUint8("valueUint8", 8)
		if _err != nil {
			return nil, errors.Wrap(_err, "Error parsing 'valueUint8' field")
		}
		valueUint8 = &_val
	}

	// Virtual field
	_isUint16 := bool((actualLength) == (2))
	isUint16 := bool(_isUint16)
	_ = isUint16

	// Optional Field (valueUint16) (Can be skipped, if a given expression evaluates to false)
	var valueUint16 *uint16 = nil
	if isUint16 {
		_val, _err := readBuffer.ReadUint16("valueUint16", 16)
		if _err != nil {
			return nil, errors.Wrap(_err, "Error parsing 'valueUint16' field")
		}
		valueUint16 = &_val
	}

	// Virtual field
	_isUint24 := bool((actualLength) == (3))
	isUint24 := bool(_isUint24)
	_ = isUint24

	// Optional Field (valueUint24) (Can be skipped, if a given expression evaluates to false)
	var valueUint24 *uint32 = nil
	if isUint24 {
		_val, _err := readBuffer.ReadUint32("valueUint24", 24)
		if _err != nil {
			return nil, errors.Wrap(_err, "Error parsing 'valueUint24' field")
		}
		valueUint24 = &_val
	}

	// Virtual field
	_isUint32 := bool((actualLength) == (4))
	isUint32 := bool(_isUint32)
	_ = isUint32

	// Optional Field (valueUint32) (Can be skipped, if a given expression evaluates to false)
	var valueUint32 *uint32 = nil
	if isUint32 {
		_val, _err := readBuffer.ReadUint32("valueUint32", 32)
		if _err != nil {
			return nil, errors.Wrap(_err, "Error parsing 'valueUint32' field")
		}
		valueUint32 = &_val
	}

	// Virtual field
	_isUint40 := bool((actualLength) == (5))
	isUint40 := bool(_isUint40)
	_ = isUint40

	// Optional Field (valueUint40) (Can be skipped, if a given expression evaluates to false)
	var valueUint40 *uint64 = nil
	if isUint40 {
		_val, _err := readBuffer.ReadUint64("valueUint40", 40)
		if _err != nil {
			return nil, errors.Wrap(_err, "Error parsing 'valueUint40' field")
		}
		valueUint40 = &_val
	}

	// Virtual field
	_isUint48 := bool((actualLength) == (6))
	isUint48 := bool(_isUint48)
	_ = isUint48

	// Optional Field (valueUint48) (Can be skipped, if a given expression evaluates to false)
	var valueUint48 *uint64 = nil
	if isUint48 {
		_val, _err := readBuffer.ReadUint64("valueUint48", 48)
		if _err != nil {
			return nil, errors.Wrap(_err, "Error parsing 'valueUint48' field")
		}
		valueUint48 = &_val
	}

	// Virtual field
	_isUint56 := bool((actualLength) == (7))
	isUint56 := bool(_isUint56)
	_ = isUint56

	// Optional Field (valueUint56) (Can be skipped, if a given expression evaluates to false)
	var valueUint56 *uint64 = nil
	if isUint56 {
		_val, _err := readBuffer.ReadUint64("valueUint56", 56)
		if _err != nil {
			return nil, errors.Wrap(_err, "Error parsing 'valueUint56' field")
		}
		valueUint56 = &_val
	}

	// Virtual field
	_isUint64 := bool((actualLength) == (8))
	isUint64 := bool(_isUint64)
	_ = isUint64

	// Optional Field (valueUint64) (Can be skipped, if a given expression evaluates to false)
	var valueUint64 *uint64 = nil
	if isUint64 {
		_val, _err := readBuffer.ReadUint64("valueUint64", 64)
		if _err != nil {
			return nil, errors.Wrap(_err, "Error parsing 'valueUint64' field")
		}
		valueUint64 = &_val
	}

	// Virtual field
	_actualValue := utils.InlineIf(isUint8, func() interface{} { return uint64((*valueUint8)) }, func() interface{} {
		return uint64(uint64(utils.InlineIf(isUint16, func() interface{} { return uint64((*valueUint16)) }, func() interface{} {
			return uint64(uint64(utils.InlineIf(isUint24, func() interface{} { return uint64((*valueUint24)) }, func() interface{} {
				return uint64(uint64(utils.InlineIf(isUint32, func() interface{} { return uint64((*valueUint32)) }, func() interface{} {
					return uint64(uint64(utils.InlineIf(isUint40, func() interface{} { return uint64((*valueUint40)) }, func() interface{} {
						return uint64(uint64(utils.InlineIf(isUint48, func() interface{} { return uint64((*valueUint48)) }, func() interface{} {
							return uint64(uint64(utils.InlineIf(isUint56, func() interface{} { return uint64((*valueUint56)) }, func() interface{} { return uint64((*valueUint64)) }).(uint64)))
						}).(uint64)))
					}).(uint64)))
				}).(uint64)))
			}).(uint64)))
		}).(uint64)))
	}).(uint64)
	actualValue := uint64(_actualValue)
	_ = actualValue

	if closeErr := readBuffer.CloseContext("BACnetTagPayloadUnsignedInteger"); closeErr != nil {
		return nil, closeErr
	}

	// Create the instance
	return NewBACnetTagPayloadUnsignedInteger(valueUint8, valueUint16, valueUint24, valueUint32, valueUint40, valueUint48, valueUint56, valueUint64, actualLength), nil
}

func (m *BACnetTagPayloadUnsignedInteger) Serialize(writeBuffer utils.WriteBuffer) error {
	if pushErr := writeBuffer.PushContext("BACnetTagPayloadUnsignedInteger"); pushErr != nil {
		return pushErr
	}
	// Virtual field
	if _isUint8Err := writeBuffer.WriteVirtual("isUint8", m.GetIsUint8()); _isUint8Err != nil {
		return errors.Wrap(_isUint8Err, "Error serializing 'isUint8' field")
	}

	// Optional Field (valueUint8) (Can be skipped, if the value is null)
	var valueUint8 *uint8 = nil
	if m.ValueUint8 != nil {
		valueUint8 = m.ValueUint8
		_valueUint8Err := writeBuffer.WriteUint8("valueUint8", 8, *(valueUint8))
		if _valueUint8Err != nil {
			return errors.Wrap(_valueUint8Err, "Error serializing 'valueUint8' field")
		}
	}
	// Virtual field
	if _isUint16Err := writeBuffer.WriteVirtual("isUint16", m.GetIsUint16()); _isUint16Err != nil {
		return errors.Wrap(_isUint16Err, "Error serializing 'isUint16' field")
	}

	// Optional Field (valueUint16) (Can be skipped, if the value is null)
	var valueUint16 *uint16 = nil
	if m.ValueUint16 != nil {
		valueUint16 = m.ValueUint16
		_valueUint16Err := writeBuffer.WriteUint16("valueUint16", 16, *(valueUint16))
		if _valueUint16Err != nil {
			return errors.Wrap(_valueUint16Err, "Error serializing 'valueUint16' field")
		}
	}
	// Virtual field
	if _isUint24Err := writeBuffer.WriteVirtual("isUint24", m.GetIsUint24()); _isUint24Err != nil {
		return errors.Wrap(_isUint24Err, "Error serializing 'isUint24' field")
	}

	// Optional Field (valueUint24) (Can be skipped, if the value is null)
	var valueUint24 *uint32 = nil
	if m.ValueUint24 != nil {
		valueUint24 = m.ValueUint24
		_valueUint24Err := writeBuffer.WriteUint32("valueUint24", 24, *(valueUint24))
		if _valueUint24Err != nil {
			return errors.Wrap(_valueUint24Err, "Error serializing 'valueUint24' field")
		}
	}
	// Virtual field
	if _isUint32Err := writeBuffer.WriteVirtual("isUint32", m.GetIsUint32()); _isUint32Err != nil {
		return errors.Wrap(_isUint32Err, "Error serializing 'isUint32' field")
	}

	// Optional Field (valueUint32) (Can be skipped, if the value is null)
	var valueUint32 *uint32 = nil
	if m.ValueUint32 != nil {
		valueUint32 = m.ValueUint32
		_valueUint32Err := writeBuffer.WriteUint32("valueUint32", 32, *(valueUint32))
		if _valueUint32Err != nil {
			return errors.Wrap(_valueUint32Err, "Error serializing 'valueUint32' field")
		}
	}
	// Virtual field
	if _isUint40Err := writeBuffer.WriteVirtual("isUint40", m.GetIsUint40()); _isUint40Err != nil {
		return errors.Wrap(_isUint40Err, "Error serializing 'isUint40' field")
	}

	// Optional Field (valueUint40) (Can be skipped, if the value is null)
	var valueUint40 *uint64 = nil
	if m.ValueUint40 != nil {
		valueUint40 = m.ValueUint40
		_valueUint40Err := writeBuffer.WriteUint64("valueUint40", 40, *(valueUint40))
		if _valueUint40Err != nil {
			return errors.Wrap(_valueUint40Err, "Error serializing 'valueUint40' field")
		}
	}
	// Virtual field
	if _isUint48Err := writeBuffer.WriteVirtual("isUint48", m.GetIsUint48()); _isUint48Err != nil {
		return errors.Wrap(_isUint48Err, "Error serializing 'isUint48' field")
	}

	// Optional Field (valueUint48) (Can be skipped, if the value is null)
	var valueUint48 *uint64 = nil
	if m.ValueUint48 != nil {
		valueUint48 = m.ValueUint48
		_valueUint48Err := writeBuffer.WriteUint64("valueUint48", 48, *(valueUint48))
		if _valueUint48Err != nil {
			return errors.Wrap(_valueUint48Err, "Error serializing 'valueUint48' field")
		}
	}
	// Virtual field
	if _isUint56Err := writeBuffer.WriteVirtual("isUint56", m.GetIsUint56()); _isUint56Err != nil {
		return errors.Wrap(_isUint56Err, "Error serializing 'isUint56' field")
	}

	// Optional Field (valueUint56) (Can be skipped, if the value is null)
	var valueUint56 *uint64 = nil
	if m.ValueUint56 != nil {
		valueUint56 = m.ValueUint56
		_valueUint56Err := writeBuffer.WriteUint64("valueUint56", 56, *(valueUint56))
		if _valueUint56Err != nil {
			return errors.Wrap(_valueUint56Err, "Error serializing 'valueUint56' field")
		}
	}
	// Virtual field
	if _isUint64Err := writeBuffer.WriteVirtual("isUint64", m.GetIsUint64()); _isUint64Err != nil {
		return errors.Wrap(_isUint64Err, "Error serializing 'isUint64' field")
	}

	// Optional Field (valueUint64) (Can be skipped, if the value is null)
	var valueUint64 *uint64 = nil
	if m.ValueUint64 != nil {
		valueUint64 = m.ValueUint64
		_valueUint64Err := writeBuffer.WriteUint64("valueUint64", 64, *(valueUint64))
		if _valueUint64Err != nil {
			return errors.Wrap(_valueUint64Err, "Error serializing 'valueUint64' field")
		}
	}
	// Virtual field
	if _actualValueErr := writeBuffer.WriteVirtual("actualValue", m.GetActualValue()); _actualValueErr != nil {
		return errors.Wrap(_actualValueErr, "Error serializing 'actualValue' field")
	}

	if popErr := writeBuffer.PopContext("BACnetTagPayloadUnsignedInteger"); popErr != nil {
		return popErr
	}
	return nil
}

func (m *BACnetTagPayloadUnsignedInteger) String() string {
	if m == nil {
		return "<nil>"
	}
	buffer := utils.NewBoxedWriteBufferWithOptions(true, true)
	m.Serialize(buffer)
	return buffer.GetBox().String()
}
