//
//  Licensed to the Apache Software Foundation (ASF) under one or more
//  contributor license agreements.  See the NOTICE file distributed with
//  this work for additional information regarding copyright ownership.
//  The ASF licenses this file to You under the Apache License, Version 2.0
//  (the "License"); you may not use this file except in compliance with
//  the License.  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

== Generating the Website

We are currently using the normal `Maven` build to not only generate the project artifacts, but also the projects website.



=== Deploying the Website

The PLC4X project uses Apache `gitpubsub` system for maintaining the website.

In general all content in a repos `asf-site` branch is copied to the Webservers, if that repo is registered for it.

This content in this branch is generated and maintained during the `Maven` build as part of the `site` generation.

The build system needs to check-in content to the `asf-site` branch and usually Jenkins machines don't have the permissions to push to git.

In order to be able to push to the `asf-site` git branch, a dedicated build job is configured to build on nodes with the Jenkins label `git-websites`.
Only on these machines are jobs allowed to push changes to a Git repo and here only to a branch named `asf-site`.

See https://builds.apache.org/view/M-R/job/PLC4X/job/PLC4X%20Site/ for details on the PLC4X Jenkins build job.

As soon as content is updated in the `asf-site` the `gitpubsub` mechanism will make those changes available at https://plc4x.apache.org
