//
//  Licensed to the Apache Software Foundation (ASF) under one or more
//  contributor license agreements.  See the NOTICE file distributed with
//  this work for additional information regarding copyright ownership.
//  The ASF licenses this file to You under the Apache License, Version 2.0
//  (the "License"); you may not use this file except in compliance with
//  the License.  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

== Generating the Website

The PLC4X project uses Apache `gitpubsub` system for maintaining the website.

In general all content in the repos `asf-site` branch is copied to the Webservers.

This content is generated during the `Maven` build as part of the `site` generation.

As the build system needs to check-in content to our GIT repo to the `asf-site` branch.
Jenkins doesn't have the credentials to push to repositories on all nodes. Only a small subset of the nodes are configured to do this.

In oder to be able to push the site changes, nodes with the label `git-websites` have to be used.







In order to have the `gitbox` system automatically deploy the content, we finally need to add an entry to this config file:
https://svn.apache.org/repos/infra/infrastructure/buildbot/aegis/buildmaster/master1/projects/cms.conf

As our build now requires to run on `buildbot`, we need to ensure all required software is installed on the build machine.

If something is missing, this has to be added to the following resource:
https://github.com/apache/infrastructure-puppet/blob/deployment/data/nodes/bb-slave1.apache.org.yaml