//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//

// Code generated from the mspec by plc4net-code-gen. DO NOT EDIT.

namespace org.apache.plc4net.drivers.knxnetip.readwrite.model
{
    public enum KnxDatapointMainType : ushort
    {
        DPT_UNKNOWN = 0,
        DPT_64_BIT_SET = 1,
        DPT_8_BYTE_UNSIGNED_VALUE = 2,
        DPT_8_BYTE_SIGNED_VALUE = 3,
        DPT_12_BYTE_SIGNED_VALUE = 4,
        DPT_8_BYTE_FLOAT_VALUE = 5,
        DPT_1_BIT = 6,
        DPT_1_BIT_CONTROLLED = 7,
        DPT_3_BIT_CONTROLLED = 8,
        DPT_CHARACTER = 9,
        DPT_8_BIT_UNSIGNED_VALUE = 10,
        DPT_8_BIT_SIGNED_VALUE = 11,
        DPT_2_BYTE_UNSIGNED_VALUE = 12,
        DPT_2_BYTE_SIGNED_VALUE = 13,
        DPT_2_BYTE_FLOAT_VALUE = 14,
        DPT_TIME = 15,
        DPT_DATE = 16,
        DPT_4_BYTE_UNSIGNED_VALUE = 17,
        DPT_4_BYTE_SIGNED_VALUE = 18,
        DPT_4_BYTE_FLOAT_VALUE = 19,
        DPT_ENTRANCE_ACCESS = 20,
        DPT_CHARACTER_STRING = 21,
        DPT_SCENE_NUMBER = 22,
        DPT_SCENE_CONTROL = 23,
        DPT_DATE_TIME = 24,
        DPT_1_BYTE = 25,
        DPT_8_BIT_SET = 26,
        DPT_16_BIT_SET = 27,
        DPT_2_BIT_SET = 28,
        DPT_2_NIBBLE_SET = 29,
        DPT_8_BIT_SET_2 = 30,
        DPT_32_BIT_SET = 31,
        DPT_ELECTRICAL_ENERGY = 32,
        DPT_24_TIMES_CHANNEL_ACTIVATION = 33,
        DPT_16_BIT_UNSIGNED_VALUE_AND_8_BIT_ENUM = 34,
        DPT_8_BIT_UNSIGNED_VALUE_AND_8_BIT_ENUM = 35,
        DPT_DATAPOINT_TYPE_VERSION = 36,
        DPT_ALARM_INFO = 37,
        DPT_3X_2_BYTE_FLOAT_VALUE = 38,
        DPT_SCALING_SPEED = 39,
        DPT_4_1_1_BYTE_COMBINED_INFORMATION = 40,
        DPT_MBUS_ADDRESS = 41,
        DPT_3_BYTE_COLOUR_RGB = 42,
        DPT_LANGUAGE_CODE_ISO_639_1 = 43,
        DPT_SIGNED_VALUE_WITH_CLASSIFICATION_AND_VALIDITY = 44,
        DPT_PRIORITISED_MODE_CONTROL = 45,
        DPT_CONFIGURATION_DIAGNOSTICS_16_BIT = 46,
        DPT_CONFIGURATION_DIAGNOSTICS_8_BIT = 47,
        DPT_POSITIONS = 48,
        DPT_STATUS_32_BIT = 49,
        DPT_STATUS_48_BIT = 50,
        DPT_CONVERTER_STATUS = 51,
        DPT_CONVERTER_TEST_RESULT = 52,
        DPT_BATTERY_INFORMATION = 53,
        DPT_BRIGHTNESS_COLOUR_TEMPERATURE_TRANSITION = 54,
        DPT_STATUS_24_BIT = 55,
        DPT_COLOUR_RGBW = 56,
        DPT_RELATIVE_CONTROL_RGBW = 57,
        DPT_RELATIVE_CONTROL_RGB = 58,
        DPT_F32F32 = 59,
        DPT_F16F16F16F16 = 60,
    }

    public static class KnxDatapointMainTypeExtensions
    {
        public static ushort GetNumber(this KnxDatapointMainType value) => value switch
        {
            KnxDatapointMainType.DPT_UNKNOWN => 0,
            KnxDatapointMainType.DPT_64_BIT_SET => 0,
            KnxDatapointMainType.DPT_8_BYTE_UNSIGNED_VALUE => 0,
            KnxDatapointMainType.DPT_8_BYTE_SIGNED_VALUE => 0,
            KnxDatapointMainType.DPT_12_BYTE_SIGNED_VALUE => 0,
            KnxDatapointMainType.DPT_8_BYTE_FLOAT_VALUE => 0,
            KnxDatapointMainType.DPT_1_BIT => 1,
            KnxDatapointMainType.DPT_1_BIT_CONTROLLED => 2,
            KnxDatapointMainType.DPT_3_BIT_CONTROLLED => 3,
            KnxDatapointMainType.DPT_CHARACTER => 4,
            KnxDatapointMainType.DPT_8_BIT_UNSIGNED_VALUE => 5,
            KnxDatapointMainType.DPT_8_BIT_SIGNED_VALUE => 6,
            KnxDatapointMainType.DPT_2_BYTE_UNSIGNED_VALUE => 7,
            KnxDatapointMainType.DPT_2_BYTE_SIGNED_VALUE => 8,
            KnxDatapointMainType.DPT_2_BYTE_FLOAT_VALUE => 9,
            KnxDatapointMainType.DPT_TIME => 10,
            KnxDatapointMainType.DPT_DATE => 11,
            KnxDatapointMainType.DPT_4_BYTE_UNSIGNED_VALUE => 12,
            KnxDatapointMainType.DPT_4_BYTE_SIGNED_VALUE => 13,
            KnxDatapointMainType.DPT_4_BYTE_FLOAT_VALUE => 14,
            KnxDatapointMainType.DPT_ENTRANCE_ACCESS => 15,
            KnxDatapointMainType.DPT_CHARACTER_STRING => 16,
            KnxDatapointMainType.DPT_SCENE_NUMBER => 17,
            KnxDatapointMainType.DPT_SCENE_CONTROL => 18,
            KnxDatapointMainType.DPT_DATE_TIME => 19,
            KnxDatapointMainType.DPT_1_BYTE => 20,
            KnxDatapointMainType.DPT_8_BIT_SET => 21,
            KnxDatapointMainType.DPT_16_BIT_SET => 22,
            KnxDatapointMainType.DPT_2_BIT_SET => 23,
            KnxDatapointMainType.DPT_2_NIBBLE_SET => 25,
            KnxDatapointMainType.DPT_8_BIT_SET_2 => 26,
            KnxDatapointMainType.DPT_32_BIT_SET => 27,
            KnxDatapointMainType.DPT_ELECTRICAL_ENERGY => 29,
            KnxDatapointMainType.DPT_24_TIMES_CHANNEL_ACTIVATION => 30,
            KnxDatapointMainType.DPT_16_BIT_UNSIGNED_VALUE_AND_8_BIT_ENUM => 206,
            KnxDatapointMainType.DPT_8_BIT_UNSIGNED_VALUE_AND_8_BIT_ENUM => 207,
            KnxDatapointMainType.DPT_DATAPOINT_TYPE_VERSION => 217,
            KnxDatapointMainType.DPT_ALARM_INFO => 219,
            KnxDatapointMainType.DPT_3X_2_BYTE_FLOAT_VALUE => 222,
            KnxDatapointMainType.DPT_SCALING_SPEED => 225,
            KnxDatapointMainType.DPT_4_1_1_BYTE_COMBINED_INFORMATION => 229,
            KnxDatapointMainType.DPT_MBUS_ADDRESS => 230,
            KnxDatapointMainType.DPT_3_BYTE_COLOUR_RGB => 232,
            KnxDatapointMainType.DPT_LANGUAGE_CODE_ISO_639_1 => 234,
            KnxDatapointMainType.DPT_SIGNED_VALUE_WITH_CLASSIFICATION_AND_VALIDITY => 235,
            KnxDatapointMainType.DPT_PRIORITISED_MODE_CONTROL => 236,
            KnxDatapointMainType.DPT_CONFIGURATION_DIAGNOSTICS_16_BIT => 237,
            KnxDatapointMainType.DPT_CONFIGURATION_DIAGNOSTICS_8_BIT => 238,
            KnxDatapointMainType.DPT_POSITIONS => 240,
            KnxDatapointMainType.DPT_STATUS_32_BIT => 241,
            KnxDatapointMainType.DPT_STATUS_48_BIT => 242,
            KnxDatapointMainType.DPT_CONVERTER_STATUS => 244,
            KnxDatapointMainType.DPT_CONVERTER_TEST_RESULT => 245,
            KnxDatapointMainType.DPT_BATTERY_INFORMATION => 246,
            KnxDatapointMainType.DPT_BRIGHTNESS_COLOUR_TEMPERATURE_TRANSITION => 249,
            KnxDatapointMainType.DPT_STATUS_24_BIT => 250,
            KnxDatapointMainType.DPT_COLOUR_RGBW => 251,
            KnxDatapointMainType.DPT_RELATIVE_CONTROL_RGBW => 252,
            KnxDatapointMainType.DPT_RELATIVE_CONTROL_RGB => 254,
            KnxDatapointMainType.DPT_F32F32 => 255,
            KnxDatapointMainType.DPT_F16F16F16F16 => 275,
            _ => default,
        };
        public static byte GetSizeInBits(this KnxDatapointMainType value) => value switch
        {
            KnxDatapointMainType.DPT_UNKNOWN => 0,
            KnxDatapointMainType.DPT_64_BIT_SET => 64,
            KnxDatapointMainType.DPT_8_BYTE_UNSIGNED_VALUE => 64,
            KnxDatapointMainType.DPT_8_BYTE_SIGNED_VALUE => 64,
            KnxDatapointMainType.DPT_12_BYTE_SIGNED_VALUE => 96,
            KnxDatapointMainType.DPT_8_BYTE_FLOAT_VALUE => 64,
            KnxDatapointMainType.DPT_1_BIT => 1,
            KnxDatapointMainType.DPT_1_BIT_CONTROLLED => 2,
            KnxDatapointMainType.DPT_3_BIT_CONTROLLED => 4,
            KnxDatapointMainType.DPT_CHARACTER => 8,
            KnxDatapointMainType.DPT_8_BIT_UNSIGNED_VALUE => 8,
            KnxDatapointMainType.DPT_8_BIT_SIGNED_VALUE => 8,
            KnxDatapointMainType.DPT_2_BYTE_UNSIGNED_VALUE => 16,
            KnxDatapointMainType.DPT_2_BYTE_SIGNED_VALUE => 16,
            KnxDatapointMainType.DPT_2_BYTE_FLOAT_VALUE => 16,
            KnxDatapointMainType.DPT_TIME => 24,
            KnxDatapointMainType.DPT_DATE => 24,
            KnxDatapointMainType.DPT_4_BYTE_UNSIGNED_VALUE => 32,
            KnxDatapointMainType.DPT_4_BYTE_SIGNED_VALUE => 32,
            KnxDatapointMainType.DPT_4_BYTE_FLOAT_VALUE => 32,
            KnxDatapointMainType.DPT_ENTRANCE_ACCESS => 32,
            KnxDatapointMainType.DPT_CHARACTER_STRING => 112,
            KnxDatapointMainType.DPT_SCENE_NUMBER => 8,
            KnxDatapointMainType.DPT_SCENE_CONTROL => 8,
            KnxDatapointMainType.DPT_DATE_TIME => 64,
            KnxDatapointMainType.DPT_1_BYTE => 8,
            KnxDatapointMainType.DPT_8_BIT_SET => 8,
            KnxDatapointMainType.DPT_16_BIT_SET => 16,
            KnxDatapointMainType.DPT_2_BIT_SET => 2,
            KnxDatapointMainType.DPT_2_NIBBLE_SET => 8,
            KnxDatapointMainType.DPT_8_BIT_SET_2 => 8,
            KnxDatapointMainType.DPT_32_BIT_SET => 32,
            KnxDatapointMainType.DPT_ELECTRICAL_ENERGY => 64,
            KnxDatapointMainType.DPT_24_TIMES_CHANNEL_ACTIVATION => 24,
            KnxDatapointMainType.DPT_16_BIT_UNSIGNED_VALUE_AND_8_BIT_ENUM => 24,
            KnxDatapointMainType.DPT_8_BIT_UNSIGNED_VALUE_AND_8_BIT_ENUM => 16,
            KnxDatapointMainType.DPT_DATAPOINT_TYPE_VERSION => 16,
            KnxDatapointMainType.DPT_ALARM_INFO => 48,
            KnxDatapointMainType.DPT_3X_2_BYTE_FLOAT_VALUE => 48,
            KnxDatapointMainType.DPT_SCALING_SPEED => 24,
            KnxDatapointMainType.DPT_4_1_1_BYTE_COMBINED_INFORMATION => 48,
            KnxDatapointMainType.DPT_MBUS_ADDRESS => 64,
            KnxDatapointMainType.DPT_3_BYTE_COLOUR_RGB => 24,
            KnxDatapointMainType.DPT_LANGUAGE_CODE_ISO_639_1 => 16,
            KnxDatapointMainType.DPT_SIGNED_VALUE_WITH_CLASSIFICATION_AND_VALIDITY => 48,
            KnxDatapointMainType.DPT_PRIORITISED_MODE_CONTROL => 8,
            KnxDatapointMainType.DPT_CONFIGURATION_DIAGNOSTICS_16_BIT => 16,
            KnxDatapointMainType.DPT_CONFIGURATION_DIAGNOSTICS_8_BIT => 8,
            KnxDatapointMainType.DPT_POSITIONS => 24,
            KnxDatapointMainType.DPT_STATUS_32_BIT => 32,
            KnxDatapointMainType.DPT_STATUS_48_BIT => 48,
            KnxDatapointMainType.DPT_CONVERTER_STATUS => 16,
            KnxDatapointMainType.DPT_CONVERTER_TEST_RESULT => 48,
            KnxDatapointMainType.DPT_BATTERY_INFORMATION => 16,
            KnxDatapointMainType.DPT_BRIGHTNESS_COLOUR_TEMPERATURE_TRANSITION => 48,
            KnxDatapointMainType.DPT_STATUS_24_BIT => 24,
            KnxDatapointMainType.DPT_COLOUR_RGBW => 48,
            KnxDatapointMainType.DPT_RELATIVE_CONTROL_RGBW => 40,
            KnxDatapointMainType.DPT_RELATIVE_CONTROL_RGB => 24,
            KnxDatapointMainType.DPT_F32F32 => 64,
            KnxDatapointMainType.DPT_F16F16F16F16 => 64,
            _ => default,
        };
        public static string GetName(this KnxDatapointMainType value) => value switch
        {
            KnxDatapointMainType.DPT_UNKNOWN => "Unknown Datapoint Type",
            KnxDatapointMainType.DPT_64_BIT_SET => "Unknown Datapoint Type",
            KnxDatapointMainType.DPT_8_BYTE_UNSIGNED_VALUE => "Unknown Datapoint Type",
            KnxDatapointMainType.DPT_8_BYTE_SIGNED_VALUE => "Unknown Datapoint Type",
            KnxDatapointMainType.DPT_12_BYTE_SIGNED_VALUE => "Unknown Datapoint Type",
            KnxDatapointMainType.DPT_8_BYTE_FLOAT_VALUE => "Unknown Datapoint Type",
            KnxDatapointMainType.DPT_1_BIT => "1-bit",
            KnxDatapointMainType.DPT_1_BIT_CONTROLLED => "1-bit controlled",
            KnxDatapointMainType.DPT_3_BIT_CONTROLLED => "3-bit controlled",
            KnxDatapointMainType.DPT_CHARACTER => "character",
            KnxDatapointMainType.DPT_8_BIT_UNSIGNED_VALUE => "8-bit unsigned value",
            KnxDatapointMainType.DPT_8_BIT_SIGNED_VALUE => "8-bit signed value",
            KnxDatapointMainType.DPT_2_BYTE_UNSIGNED_VALUE => "2-byte unsigned value",
            KnxDatapointMainType.DPT_2_BYTE_SIGNED_VALUE => "2-byte signed value",
            KnxDatapointMainType.DPT_2_BYTE_FLOAT_VALUE => "2-byte float value",
            KnxDatapointMainType.DPT_TIME => "time",
            KnxDatapointMainType.DPT_DATE => "date",
            KnxDatapointMainType.DPT_4_BYTE_UNSIGNED_VALUE => "4-byte unsigned value",
            KnxDatapointMainType.DPT_4_BYTE_SIGNED_VALUE => "4-byte signed value",
            KnxDatapointMainType.DPT_4_BYTE_FLOAT_VALUE => "4-byte float value",
            KnxDatapointMainType.DPT_ENTRANCE_ACCESS => "entrance access",
            KnxDatapointMainType.DPT_CHARACTER_STRING => "character string",
            KnxDatapointMainType.DPT_SCENE_NUMBER => "scene number",
            KnxDatapointMainType.DPT_SCENE_CONTROL => "scene control",
            KnxDatapointMainType.DPT_DATE_TIME => "Date Time",
            KnxDatapointMainType.DPT_1_BYTE => "1-byte",
            KnxDatapointMainType.DPT_8_BIT_SET => "8-bit set",
            KnxDatapointMainType.DPT_16_BIT_SET => "16-bit set",
            KnxDatapointMainType.DPT_2_BIT_SET => "2-bit set",
            KnxDatapointMainType.DPT_2_NIBBLE_SET => "2-nibble set",
            KnxDatapointMainType.DPT_8_BIT_SET_2 => "8-bit set",
            KnxDatapointMainType.DPT_32_BIT_SET => "32-bit set",
            KnxDatapointMainType.DPT_ELECTRICAL_ENERGY => "electrical energy",
            KnxDatapointMainType.DPT_24_TIMES_CHANNEL_ACTIVATION => "24 times channel activation",
            KnxDatapointMainType.DPT_16_BIT_UNSIGNED_VALUE_AND_8_BIT_ENUM => "16-bit unsigned value & 8-bit enum",
            KnxDatapointMainType.DPT_8_BIT_UNSIGNED_VALUE_AND_8_BIT_ENUM => "8-bit unsigned value & 8-bit enum",
            KnxDatapointMainType.DPT_DATAPOINT_TYPE_VERSION => "datapoint type version",
            KnxDatapointMainType.DPT_ALARM_INFO => "alarm info",
            KnxDatapointMainType.DPT_3X_2_BYTE_FLOAT_VALUE => "3x 2-byte float value",
            KnxDatapointMainType.DPT_SCALING_SPEED => "scaling speed",
            KnxDatapointMainType.DPT_4_1_1_BYTE_COMBINED_INFORMATION => "4-1-1 byte combined information",
            KnxDatapointMainType.DPT_MBUS_ADDRESS => "MBus address",
            KnxDatapointMainType.DPT_3_BYTE_COLOUR_RGB => "3-byte colour RGB",
            KnxDatapointMainType.DPT_LANGUAGE_CODE_ISO_639_1 => "language code ISO 639-1",
            KnxDatapointMainType.DPT_SIGNED_VALUE_WITH_CLASSIFICATION_AND_VALIDITY => "Signed value with classification and validity",
            KnxDatapointMainType.DPT_PRIORITISED_MODE_CONTROL => "Prioritised Mode Control",
            KnxDatapointMainType.DPT_CONFIGURATION_DIAGNOSTICS_16_BIT => "configuration/ diagnostics",
            KnxDatapointMainType.DPT_CONFIGURATION_DIAGNOSTICS_8_BIT => "configuration/ diagnostics",
            KnxDatapointMainType.DPT_POSITIONS => "positions",
            KnxDatapointMainType.DPT_STATUS_32_BIT => "status",
            KnxDatapointMainType.DPT_STATUS_48_BIT => "status",
            KnxDatapointMainType.DPT_CONVERTER_STATUS => "Converter Status",
            KnxDatapointMainType.DPT_CONVERTER_TEST_RESULT => "Converter test result",
            KnxDatapointMainType.DPT_BATTERY_INFORMATION => "Battery Information",
            KnxDatapointMainType.DPT_BRIGHTNESS_COLOUR_TEMPERATURE_TRANSITION => "brightness colour temperature transition",
            KnxDatapointMainType.DPT_STATUS_24_BIT => "status",
            KnxDatapointMainType.DPT_COLOUR_RGBW => "Colour RGBW",
            KnxDatapointMainType.DPT_RELATIVE_CONTROL_RGBW => "Relative Control RGBW",
            KnxDatapointMainType.DPT_RELATIVE_CONTROL_RGB => "Relative Control RGB",
            KnxDatapointMainType.DPT_F32F32 => "F32F32",
            KnxDatapointMainType.DPT_F16F16F16F16 => "F16F16F16F16",
            _ => default,
        };
    }
}
