//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//

// Code generated from the mspec by plc4net-code-gen. DO NOT EDIT.

namespace org.apache.plc4net.drivers.knxnetip.readwrite.model
{
    public enum KnxPropertyDataType : byte
    {
        PDT_UNKNOWN = 0,
        PDT_CONTROL = 1,
        PDT_CHAR = 2,
        PDT_UNSIGNED_CHAR = 3,
        PDT_INT = 4,
        PDT_UNSIGNED_INT = 5,
        PDT_KNX_FLOAT = 6,
        PDT_DATE = 7,
        PDT_TIME = 8,
        PDT_LONG = 9,
        PDT_UNSIGNED_LONG = 10,
        PDT_FLOAT = 11,
        PDT_DOUBLE = 12,
        PDT_CHAR_BLOCK = 13,
        PDT_POLL_GROUP_SETTINGS = 14,
        PDT_SHORT_CHAR_BLOCK = 15,
        PDT_DATE_TIME = 16,
        PDT_VARIABLE_LENGTH = 17,
        PDT_GENERIC_01 = 18,
        PDT_GENERIC_02 = 19,
        PDT_GENERIC_03 = 20,
        PDT_GENERIC_04 = 21,
        PDT_GENERIC_05 = 22,
        PDT_GENERIC_06 = 23,
        PDT_GENERIC_07 = 24,
        PDT_GENERIC_08 = 25,
        PDT_GENERIC_09 = 26,
        PDT_GENERIC_10 = 27,
        PDT_GENERIC_11 = 28,
        PDT_GENERIC_12 = 29,
        PDT_GENERIC_13 = 30,
        PDT_GENERIC_14 = 31,
        PDT_GENERIC_15 = 32,
        PDT_GENERIC_16 = 33,
        PDT_GENERIC_17 = 34,
        PDT_GENERIC_18 = 35,
        PDT_GENERIC_19 = 36,
        PDT_GENERIC_20 = 37,
        PDT_UTF_8 = 38,
        PDT_VERSION = 39,
        PDT_ALARM_INFO = 40,
        PDT_BINARY_INFORMATION = 41,
        PDT_BITSET8 = 42,
        PDT_BITSET16 = 43,
        PDT_ENUM8 = 44,
        PDT_SCALING = 45,
        PDT_NE_VL = 46,
        PDT_NE_FL = 47,
        PDT_FUNCTION = 48,
        PDT_ESCAPE = 49,
    }

    public static class KnxPropertyDataTypeExtensions
    {
        public static byte GetNumber(this KnxPropertyDataType value) => value switch
        {
            KnxPropertyDataType.PDT_UNKNOWN => 0,
            KnxPropertyDataType.PDT_CONTROL => 0,
            KnxPropertyDataType.PDT_CHAR => 1,
            KnxPropertyDataType.PDT_UNSIGNED_CHAR => 2,
            KnxPropertyDataType.PDT_INT => 3,
            KnxPropertyDataType.PDT_UNSIGNED_INT => 4,
            KnxPropertyDataType.PDT_KNX_FLOAT => 5,
            KnxPropertyDataType.PDT_DATE => 6,
            KnxPropertyDataType.PDT_TIME => 7,
            KnxPropertyDataType.PDT_LONG => 8,
            KnxPropertyDataType.PDT_UNSIGNED_LONG => 9,
            KnxPropertyDataType.PDT_FLOAT => 10,
            KnxPropertyDataType.PDT_DOUBLE => 11,
            KnxPropertyDataType.PDT_CHAR_BLOCK => 12,
            KnxPropertyDataType.PDT_POLL_GROUP_SETTINGS => 13,
            KnxPropertyDataType.PDT_SHORT_CHAR_BLOCK => 14,
            KnxPropertyDataType.PDT_DATE_TIME => 15,
            KnxPropertyDataType.PDT_VARIABLE_LENGTH => 16,
            KnxPropertyDataType.PDT_GENERIC_01 => 17,
            KnxPropertyDataType.PDT_GENERIC_02 => 18,
            KnxPropertyDataType.PDT_GENERIC_03 => 19,
            KnxPropertyDataType.PDT_GENERIC_04 => 20,
            KnxPropertyDataType.PDT_GENERIC_05 => 21,
            KnxPropertyDataType.PDT_GENERIC_06 => 22,
            KnxPropertyDataType.PDT_GENERIC_07 => 23,
            KnxPropertyDataType.PDT_GENERIC_08 => 24,
            KnxPropertyDataType.PDT_GENERIC_09 => 25,
            KnxPropertyDataType.PDT_GENERIC_10 => 26,
            KnxPropertyDataType.PDT_GENERIC_11 => 27,
            KnxPropertyDataType.PDT_GENERIC_12 => 28,
            KnxPropertyDataType.PDT_GENERIC_13 => 29,
            KnxPropertyDataType.PDT_GENERIC_14 => 30,
            KnxPropertyDataType.PDT_GENERIC_15 => 31,
            KnxPropertyDataType.PDT_GENERIC_16 => 32,
            KnxPropertyDataType.PDT_GENERIC_17 => 33,
            KnxPropertyDataType.PDT_GENERIC_18 => 34,
            KnxPropertyDataType.PDT_GENERIC_19 => 35,
            KnxPropertyDataType.PDT_GENERIC_20 => 36,
            KnxPropertyDataType.PDT_UTF_8 => 47,
            KnxPropertyDataType.PDT_VERSION => 48,
            KnxPropertyDataType.PDT_ALARM_INFO => 49,
            KnxPropertyDataType.PDT_BINARY_INFORMATION => 50,
            KnxPropertyDataType.PDT_BITSET8 => 51,
            KnxPropertyDataType.PDT_BITSET16 => 52,
            KnxPropertyDataType.PDT_ENUM8 => 53,
            KnxPropertyDataType.PDT_SCALING => 54,
            KnxPropertyDataType.PDT_NE_VL => 60,
            KnxPropertyDataType.PDT_NE_FL => 61,
            KnxPropertyDataType.PDT_FUNCTION => 62,
            KnxPropertyDataType.PDT_ESCAPE => 63,
            _ => default,
        };
        public static byte GetSizeInBytes(this KnxPropertyDataType value) => value switch
        {
            KnxPropertyDataType.PDT_UNKNOWN => 0,
            KnxPropertyDataType.PDT_CONTROL => 10,
            KnxPropertyDataType.PDT_CHAR => 1,
            KnxPropertyDataType.PDT_UNSIGNED_CHAR => 1,
            KnxPropertyDataType.PDT_INT => 2,
            KnxPropertyDataType.PDT_UNSIGNED_INT => 2,
            KnxPropertyDataType.PDT_KNX_FLOAT => 2,
            KnxPropertyDataType.PDT_DATE => 3,
            KnxPropertyDataType.PDT_TIME => 3,
            KnxPropertyDataType.PDT_LONG => 4,
            KnxPropertyDataType.PDT_UNSIGNED_LONG => 4,
            KnxPropertyDataType.PDT_FLOAT => 4,
            KnxPropertyDataType.PDT_DOUBLE => 8,
            KnxPropertyDataType.PDT_CHAR_BLOCK => 10,
            KnxPropertyDataType.PDT_POLL_GROUP_SETTINGS => 3,
            KnxPropertyDataType.PDT_SHORT_CHAR_BLOCK => 5,
            KnxPropertyDataType.PDT_DATE_TIME => 8,
            KnxPropertyDataType.PDT_VARIABLE_LENGTH => 0,
            KnxPropertyDataType.PDT_GENERIC_01 => 1,
            KnxPropertyDataType.PDT_GENERIC_02 => 2,
            KnxPropertyDataType.PDT_GENERIC_03 => 3,
            KnxPropertyDataType.PDT_GENERIC_04 => 4,
            KnxPropertyDataType.PDT_GENERIC_05 => 5,
            KnxPropertyDataType.PDT_GENERIC_06 => 6,
            KnxPropertyDataType.PDT_GENERIC_07 => 7,
            KnxPropertyDataType.PDT_GENERIC_08 => 8,
            KnxPropertyDataType.PDT_GENERIC_09 => 9,
            KnxPropertyDataType.PDT_GENERIC_10 => 10,
            KnxPropertyDataType.PDT_GENERIC_11 => 11,
            KnxPropertyDataType.PDT_GENERIC_12 => 12,
            KnxPropertyDataType.PDT_GENERIC_13 => 13,
            KnxPropertyDataType.PDT_GENERIC_14 => 14,
            KnxPropertyDataType.PDT_GENERIC_15 => 15,
            KnxPropertyDataType.PDT_GENERIC_16 => 16,
            KnxPropertyDataType.PDT_GENERIC_17 => 17,
            KnxPropertyDataType.PDT_GENERIC_18 => 18,
            KnxPropertyDataType.PDT_GENERIC_19 => 19,
            KnxPropertyDataType.PDT_GENERIC_20 => 20,
            KnxPropertyDataType.PDT_UTF_8 => 0,
            KnxPropertyDataType.PDT_VERSION => 2,
            KnxPropertyDataType.PDT_ALARM_INFO => 6,
            KnxPropertyDataType.PDT_BINARY_INFORMATION => 1,
            KnxPropertyDataType.PDT_BITSET8 => 1,
            KnxPropertyDataType.PDT_BITSET16 => 2,
            KnxPropertyDataType.PDT_ENUM8 => 1,
            KnxPropertyDataType.PDT_SCALING => 1,
            KnxPropertyDataType.PDT_NE_VL => 0,
            KnxPropertyDataType.PDT_NE_FL => 0,
            KnxPropertyDataType.PDT_FUNCTION => 0,
            KnxPropertyDataType.PDT_ESCAPE => 0,
            _ => default,
        };
        public static string GetName(this KnxPropertyDataType value) => value switch
        {
            KnxPropertyDataType.PDT_UNKNOWN => "Unknown Property Data Type",
            KnxPropertyDataType.PDT_CONTROL => "PDT_CONTROL",
            KnxPropertyDataType.PDT_CHAR => "PDT_CHAR",
            KnxPropertyDataType.PDT_UNSIGNED_CHAR => "PDT_UNSIGNED_CHAR",
            KnxPropertyDataType.PDT_INT => "PDT_INT",
            KnxPropertyDataType.PDT_UNSIGNED_INT => "PDT_UNSIGNED_INT",
            KnxPropertyDataType.PDT_KNX_FLOAT => "PDT_KNX_FLOAT",
            KnxPropertyDataType.PDT_DATE => "PDT_DATE",
            KnxPropertyDataType.PDT_TIME => "PDT_TIME",
            KnxPropertyDataType.PDT_LONG => "PDT_LONG",
            KnxPropertyDataType.PDT_UNSIGNED_LONG => "PDT_UNSIGNED_LONG",
            KnxPropertyDataType.PDT_FLOAT => "PDT_FLOAT",
            KnxPropertyDataType.PDT_DOUBLE => "PDT_DOUBLE",
            KnxPropertyDataType.PDT_CHAR_BLOCK => "PDT_CHAR_BLOCK",
            KnxPropertyDataType.PDT_POLL_GROUP_SETTINGS => "PDT_POLL_GROUP_SETTINGS",
            KnxPropertyDataType.PDT_SHORT_CHAR_BLOCK => "PDT_SHORT_CHAR_BLOCK",
            KnxPropertyDataType.PDT_DATE_TIME => "PDT_DATE_TIME",
            KnxPropertyDataType.PDT_VARIABLE_LENGTH => "PDT_VARIABLE_LENGTH",
            KnxPropertyDataType.PDT_GENERIC_01 => "PDT_GENERIC_01",
            KnxPropertyDataType.PDT_GENERIC_02 => "PDT_GENERIC_02",
            KnxPropertyDataType.PDT_GENERIC_03 => "PDT_GENERIC_03",
            KnxPropertyDataType.PDT_GENERIC_04 => "PDT_GENERIC_04",
            KnxPropertyDataType.PDT_GENERIC_05 => "PDT_GENERIC_05",
            KnxPropertyDataType.PDT_GENERIC_06 => "PDT_GENERIC_06",
            KnxPropertyDataType.PDT_GENERIC_07 => "PDT_GENERIC_07",
            KnxPropertyDataType.PDT_GENERIC_08 => "PDT_GENERIC_08",
            KnxPropertyDataType.PDT_GENERIC_09 => "PDT_GENERIC_09",
            KnxPropertyDataType.PDT_GENERIC_10 => "PDT_GENERIC_10",
            KnxPropertyDataType.PDT_GENERIC_11 => "PDT_GENERIC_11",
            KnxPropertyDataType.PDT_GENERIC_12 => "PDT_GENERIC_12",
            KnxPropertyDataType.PDT_GENERIC_13 => "PDT_GENERIC_13",
            KnxPropertyDataType.PDT_GENERIC_14 => "PDT_GENERIC_14",
            KnxPropertyDataType.PDT_GENERIC_15 => "PDT_GENERIC_15",
            KnxPropertyDataType.PDT_GENERIC_16 => "PDT_GENERIC_16",
            KnxPropertyDataType.PDT_GENERIC_17 => "PDT_GENERIC_17",
            KnxPropertyDataType.PDT_GENERIC_18 => "PDT_GENERIC_18",
            KnxPropertyDataType.PDT_GENERIC_19 => "PDT_GENERIC_19",
            KnxPropertyDataType.PDT_GENERIC_20 => "PDT_GENERIC_20",
            KnxPropertyDataType.PDT_UTF_8 => "PDT_UTF-8",
            KnxPropertyDataType.PDT_VERSION => "PDT_VERSION",
            KnxPropertyDataType.PDT_ALARM_INFO => "PDT_ALARM_INFO",
            KnxPropertyDataType.PDT_BINARY_INFORMATION => "PDT_BINARY_INFORMATION",
            KnxPropertyDataType.PDT_BITSET8 => "PDT_BITSET8",
            KnxPropertyDataType.PDT_BITSET16 => "PDT_BITSET16",
            KnxPropertyDataType.PDT_ENUM8 => "PDT_ENUM8",
            KnxPropertyDataType.PDT_SCALING => "PDT_SCALING",
            KnxPropertyDataType.PDT_NE_VL => "PDT_NE_VL",
            KnxPropertyDataType.PDT_NE_FL => "PDT_NE_FL",
            KnxPropertyDataType.PDT_FUNCTION => "PDT_FUNCTION",
            KnxPropertyDataType.PDT_ESCAPE => "PDT_ESCAPE",
            _ => default,
        };
    }
}
