//
//  Licensed to the Apache Software Foundation (ASF) under one or more
//  contributor license agreements.  See the NOTICE file distributed with
//  this work for additional information regarding copyright ownership.
//  The ASF licenses this file to You under the Apache License, Version 2.0
//  (the "License"); you may not use this file except in compliance with
//  the License.  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

= S7
:imagesdir: ../../img/

== Overview of the Protocols

[ditaa,protocols-s7-osi]
....
                    :                                                                                   :
                    :                                                                                   :
                    :                           :             :             : Profinet RT : Profinet IRT:
- - - - - - - - - - +-------------+-------------+-------------+-------------+-------------+-------------+ - -
                    |c0B0         |c0B0         |c0B0         |c0B0         |c0B0         |c0B0         |
 Application        |             |             |             |             |             |             |
 Layer              |             |             |             |             |             |             |
                    |             |             |             |             |             |             |
                    |             |             |             |             |             |             |
- - - - - - - - - - |             |             |             |             |             |             | - -
                    |             |             |             |             |             |             |
 Presentation       |             |             |             |             |             |             |
 Layer              |             |             |     S7      |             |             |             |
                    |             |             |Communication|             |  Profinet   |  Profinet   |
                    |             |             |             |             |             |             |
- - - - - - - - - - |             |             |             |             |             |             | - -
                    |             |             |             |             |             |             |
 Session            |             |             |             |             |             |             |
 Layer              |             |             |             |             |             |             |
                    |             |             |             |             |             |             |
                    |             |             |             |             |             |             |
- - - - - - - - - - +-------------+-------------+-------------+-------------+-------------+-------------+ - -
                    |cAAA         |cAAA         |cF6F                       |c0AF         |cA0F         |
                    |             |             |  ISO Transport Protocol   |             |             |
                    |             |             |          RFC 905          |             |             |
                    |             |             | (Class 0)                 |             |             |
                    |             |             +-------------+             |             |             |
                    |             |             |cFF6         |             |             |             |
 Transport          |             |             | ISO on TCP  |             |             |             |
 Layer              |     UDP     |     TCP     |  RFC 1006   |             |             |             |
                    |             |             +-------------+             |             |             |
                    |             |                           |     ISO     |             |             |
- - - - - - - - - - +-------------+---------------------------+   Transport |             |             | - -
                    |cAAA                                     |   Protocol  |             |             |
 Network            |                                         |   RFC 905   |             |             |
 Layer              |                    IP                   |   (Class 4) |             |             |
                    |                                         |             |             |             |
                    |                                         |             |             |             |
- - - - - - - - - - +-----------------------------------------+-------------+-------------+-------------+ - -
                    |cAAA                                                                               |
 Data Link          |                                                                                   |
 Layer              |                                                                                   |
                    |                                                                                   |
                    |                       Industrial                                                  |
- - - - - - - - - - |                        Ethernet                                                   | - -
                    |                                                                                   |
 Physical           |                                                                                   |
 Layer              |                                                                                   |
                    |                                                                                   |
                    |                                                                                   |
- - - - - - - - - - +-----------------------------------------------------------------------------------+ - -
....

== Protocol Descriptions

|===
|Name |ISO |RFC |Link
|Transmission Control Protocol (TCP) |- | RFC 793 |https://tools.ietf.org/html/rfc793
|ISO Transport Protocol (Class 4) |ISO DP 8073 | RFC 905 |https://tools.ietf.org/html/rfc905
|ISO on TCP |- | RFC 1006| https://tools.ietf.org/html/rfc1006
|S7 Protocol |- |- |http://gmiru.com/article/s7comm/
|===

== Interaction with an S7 PLC

[seqdiag,s7-interaction]
....
{
    group Client {
        Client;
    }

    group PLC {
        "ISO TP";
        S7;
    }

    ... Connect ...

    Client ->  "ISO TP" [label = "Connect"]
    Client <-- "ISO TP"
    Client ->  "ISO TP" [label = "Setup Communication"]
               "ISO TP" ->  S7 [label = "Setup Communication"]
               "ISO TP" <-- S7
    Client <-- "ISO TP"

    === Read ===

    Client ->  "ISO TP" [label = "Read"]
               "ISO TP" ->  S7 [label = "Read"]
               "ISO TP" <-- S7
    Client <-- "ISO TP"

    === Write ===

    Client ->  "ISO TP" [label = "Write"]
               "ISO TP" ->  S7 [label = "Write"]
               "ISO TP" <-- S7
    Client <-- "ISO TP"
}
....

=== Structure of a Connection Request

// len (length of bits - use instead of explicit byte count - requires "*" as first element)
// label
// color / background
// linecolor
// rotate (degrees)
// colheight
// height
// numbered
// label_orientation (vertical, horizontal)
// stacked (no value)
// icon
// shape (box, circle, ...)
[packetdiag,s7-connection-request,svg]
....
{
    colwidth = 32
    //node_height = 72

    // ISO on TCP
    * ISO on TCP Magic Number (0x03) [len = 8, color = "pink"]
    * Reserved (0x00) [len = 8, color = "pink"]
    * Packet Length (including ISO on TCP header) [len = 16, color = "pink"]

    // ISO Transport Protocol
    * ISO TP Header Length\n(excluding length byte) [len = 8, color = "lightblue"]
    * TPDU-Code\n(CR = 0xE0) [len = 4, color = "lightblue"]
    * Signal CDT\n(0x00) [len = 4, color = "lightblue"]
    // ISO TP Header (Fixed Part)
    * Destination Reference [len = 16, color = "lightblue"]
    * Source Reference [len = 16, color = "lightblue"]
    * Protocol Class (Class 0 = 0x00) [len = 8, color = "lightblue"]

    // ISO TP Header (Variable Part / Parameters)
    * Parameter Code\n(TPDU Size = 0xC0) [len = 8, color = "lightblue"]
    * Parameter Length\n(1 = 0x01) [len = 8, color = "lightblue"]
    * Parameter Value\n(TPDU Size 1024 = 0x0A) [len = 8, color = "lightblue"]

    * Parameter Code\n(Calling TSAP = 0xC1) [len = 8, color = "lightblue"]
    * Parameter Length (2 = 0x02) [len = 8, color = "lightblue"]
    * Device Group:\nPG/PC (0x01) [len = 8, color = "lightblue"]
    * TSAP Id (0x00) [len = 8, color = "lightblue"]

    * Parameter Code\n(Called TSAP = 0xC2) [len = 8, color = "lightblue"]
    * Parameter Length (2 = 0x02) [len = 8, color = "lightblue"]
    * Device Group:\nOthers (0x03) [len = 8, color = "lightblue"]
    * Rack Number\n[len = 4, color = "green"]
    * Slot Number\n[len = 4, color = "green"]
}
....

== Links

- High Level description: http://snap7.sourceforge.net/siemens_comm.html
- Wireshark Documentation: https://wiki.wireshark.org/S7comm
- Some more reverse engineered documentation on the protocol: https://media.defcon.org/DEF%20CON%2025/DEF%20CON%2025%20presentations/Cheng%20Lei/DEFCON-25-Cheng-Lei-The-Spear-to-Break-the-Security-Wall-of-S7CommPlus-WP.pdf
- https://support.industry.siemens.com/cs/document/26483647/welche-eigenschaften-vorteile-und-besonderheiten-bietet-das-s7-protokoll-?dti=0&lc=de-WW
- Protocol Diagram: https://cache.industry.siemens.com/dl/files/647/26483647/img_44602/v1/net_s7_protokoll_01.gif
- Interesting presentation mentioning a new protocol flavor 0x72 instead of the old 0x32: https://www.research.ibm.com/haifa/Workshops/security2014/present/Avishai_Wool_AccurateModelingoftheSiemensS7SCADAProtocol-v5.pdf
- 0x72 Protocol decoded: https://sourceforge.net/p/s7commwireshark/code/HEAD/tree/trunk/src/s7comm_plus/packet-s7comm_plus.c
- Open Source PHP Project: http://epics.web.psi.ch/software/s7plc/