//
//  Licensed to the Apache Software Foundation (ASF) under one or more
//  contributor license agreements.  See the NOTICE file distributed with
//  this work for additional information regarding copyright ownership.
//  The ASF licenses this file to You under the Apache License, Version 2.0
//  (the "License"); you may not use this file except in compliance with
//  the License.  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
:imagesdir: ../../img/

== S7 Comm Plus (0x72)

The `S7 Comm Plus` protocol is a new version of the original `S7 Comm` protocol.
While a `S7 Comm` packet is identified, by the magic byte `0x32`, the `S7 Comm Plus` packet uses the magic byte `0x72`.
The End of a packet is indicated by a frame end sequence of 6 bytes: 00 00 72 01 00 00

The general structure of the protocols content however is completely different and far less documented.

The biggest source for getting started in implementing this protocol was the https://os-s.de/thesis/MA_Maik_Brueggemann.pdf[Master Thesis of Maik Brüggemann].
However this only covered the basic structure of a `S7 Comm Plus` packet.

=== General Structure of a Packet

[packetdiag,s7-comm-plus-packet,svg]
....
{
    colwidth = 32

    // ISO on TCP
    * ISO on TCP Magic Number (0x03) [len = 8, color = "#068D9D"]
    * Reserved (0x00) [len = 8, color = "#068D9D"]
    * Packet Length (including ISO on TCP header) [len = 16, color = "#068D9D"]

    // ISO Transport Protocol
    * ISO TP Header Length\n(excluding length byte) [len = 8, color = "#53599A"]
    * TPDU-Code\n(Data = 0xF0) [len = 4, color = "#AEECEF"]
    * Signal CDT\n(0x00) [len = 4, color = "#53599A"]
    * TPDU-NR/EOT [len = 8, color = "#53599A"]

    // S7 Comm Plus
    * S7 Comm Plus Protocol Magic Byte\n(0x72) [len = 8, color = "#6D9DC5"]
    * Version (0x01) [len = 8, color = "#6D9DC5"]
    * Length\n(including length bytes excluding frame boundary) [len = 16, color = "#6D9DC5"]
    * Type [len = 8, color = "#6D9DC5"]
    * Reserved (0x0000) [len = 16, color = "#6D9DC5"]
    * Sub-Type [len = 16, color = "#6D9DC5"]
    * Sequence Number [len = 32, color = "#6D9DC5"]
    // Undocumented constant sequence
    * 00 00 01 20 [len = 32]
    * 36 00 00 01 [len = 32]
    * 1d 00 04 00 [len = 32]
    * 00 00 00 00 [len = 32]
    * a1 00 00 00 [len = 32]
    * d3 82 1f 00 [len = 32]
    * 00 [len = 8]

    // Parameters
    * Attribute Block Magic Byte\n(0xA3) [len = 8, color = "#00FF80"]
    * Attribute Id (Type) [len = 8, color = "#00FF80"]
    * Format [len = 8, color = "#00FF80"]
    * Data Type [len = 8, color = "#00FF80"]
    * Length [len = 8, color = "#00FF80"]
    * Attribute Value [len = 56, color = "#00FF80"]

    // Parameters
    * Attribute Block Magic Byte\n(0xA3) [len = 8, color = "#0080FF"]
    * Attribute Id (Type) [len = 8, color = "#0080FF"]
    * Format [len = 8, color = "#0080FF"]
    * Data Type [len = 8, color = "#0080FF"]
    * Length [len = 8, color = "#0080FF"]
    * Attribute Value [len = 56, color = "#0080FF"]

    // Parameters
    * Attribute Block Magic Byte\n(0xA3) [len = 8, color = "#00FF80"]
    * Attribute Id (Type) [len = 8, color = "#00FF80"]
    * Format [len = 8, color = "#00FF80"]
    * Data Type [len = 8, color = "#00FF80"]
    * Length [len = 8, color = "#00FF80"]
    * Attribute Value [len = 56, color = "#00FF80"]

    // Frame End
    * Reserved (0x0000) [len = 16, color = "#FF3399"]
    * S7 Comm Plus Protocol Magic Byte\n(0x72) [len = 8, color = "#FF3399"]
    * Version (0x01) [len = 8, color = "#FF3399"]
    * Reserved (0x0000) [len = 16, color = "#FF3399"]

}
....


...
