//
//  Licensed to the Apache Software Foundation (ASF) under one or more
//  contributor license agreements.  See the NOTICE file distributed with
//  this work for additional information regarding copyright ownership.
//  The ASF licenses this file to You under the Apache License, Version 2.0
//  (the "License"); you may not use this file except in compliance with
//  the License.  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
:imagesdir: ../../img/

== S7 Comm (0x32)

=== General

While a lot of information was available on the general structure of S7 communication, only little information was available on the constant values this protocol uses.
If information was available, this was mostly provided with a GPL license and therefore was disqualified for being used in this project.
The information on the S7 constants in this project were therefore generated by a little tool that generates "pcapng" files `WireShark` can process.
The tool then generated 256 versions of a given template with the only difference being the one byte having all possible values.
Using the `tshark` commandline tool, the generated packets were decoded to an XML format.
For each examined byte an XPath expression was created to detect valid values.
As soon as a valid value was found the tool then output the detected constant value to the console.

The tool for generating this is located in the `plc4j/protocols/s7-utils` project.

=== Structure of a Setup Communication Request

[packetdiag,s7-setup-communication-request,svg]
....
{
    colwidth = 32

    // ISO on TCP
    * ISO on TCP Magic Number (0x03) [len = 8, color = "#068D9D"]
    * Reserved (0x00) [len = 8, color = "#068D9D"]
    * Packet Length (including ISO on TCP header) [len = 16, color = "#068D9D"]

    // ISO Transport Protocol
    * ISO TP Header Length\n(excluding length byte) [len = 8, color = "#53599A"]
    * TPDU-Code\n(Data = 0xF0) [len = 4, color = "#AEECEF"]
    * Signal CDT\n(0x00) [len = 4, color = "#53599A"]
    // ISO TP Header (Fixed Part)
    * Destination Reference (0x??)[len = 16, color = "#53599A"]
    * Source Reference (0x??)[len = 16, color = "#53599A"]
    * Protocol Class\n(Class 0 = 0x00) [len = 8, color = "#53599A"]

    // S7
    96-103: S7 Protocol Magic Byte (0x32) [color = "#6D9DC5"]
    * Message Type (JOB = 0x01) [len = 8, color = "#AEECEF"]
    * Reserved (0x0000) [len = 16, color = "#6D9DC5"]
    * PDU Reference (0x??)[len = 16, color = "#6D9DC5"]
    * S7 Parameters Length  (8 = 0x08) [len = 16, color = "#6D9DC5"]
    * S7 Data Length (0 = 0x00) [len = 16, color = "#6D9DC5"]

    // S7 Parameters
    * Function\n(Setup Communication = 0xF0) [len = 8, color = "#AEECEF"]
    * Reserved (0x00) [len = 8, color = "#6D9DC5"]
    * Max AMQ Caller [len = 16, color = "#80DED9"]
    * Max AMQ Callee [len = 16, color = "#80DED9"]
    * PDU Size [len = 16, color = "#80DED9"]

    // S7 Data
}
....

Legend:

- [protocolIsoOnTcp]#ISO on TCP Packet Header#
- [protocolIsoTP]#ISO Transport Protocol Packet Header#
- [protocolS7]#S7 Protocol#
- [protocolId]#Part of the packet that identifies the type of request#
- [protocolParameter]#Variable Parts of the ISO Transport Protocol Packet Header#

=== Structure of a Setup Communication Response

The `Setup Communication Response` is identical to the `Setup Communication Request` with the only difference that the `Message Type` has an ACK_DATA code of `0x03`.

Also does the response eventually provide different values for `Max AMQ Caller`, `Max AMQ Callee` and `PDU Size`.

The values might be lower than in the request, but never higher.

TIP: One thing about `Setup Communication Responses` which is kind of strange, is that usually S7 response messages have additional `error class` and `error code` fields, which this type of response doesn't seem to have.

=== Links

Providing some additional information without directly being used:

- High Level description: http://snap7.sourceforge.net/siemens_comm.html
- https://support.industry.siemens.com/cs/document/26483647/welche-eigenschaften-vorteile-und-besonderheiten-bietet-das-s7-protokoll-?dti=0&lc=de-WW
- Interesting presentation mentioning a new protocol flavor 0x72 instead of the old 0x32: https://www.research.ibm.com/haifa/Workshops/security2014/present/Avishai_Wool_AccurateModelingoftheSiemensS7SCADAProtocol-v5.pdf
- Open Source SCADA System: https://www.eclipse.org/eclipsescada/