//
//  Licensed to the Apache Software Foundation (ASF) under one or more
//  contributor license agreements.  See the NOTICE file distributed with
//  this work for additional information regarding copyright ownership.
//  The ASF licenses this file to You under the Apache License, Version 2.0
//  (the "License"); you may not use this file except in compliance with
//  the License.  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
:imagesdir: ../../images/
:icons: font

== Connection Pool

There are situations where you don't want to carry around connections in your code.

For example if you have a microservice application, you might have multiple services accessing PLC data.

Keeping an open connection for each of these is rather problematic as in contrast to modern computers, PLCs usually are only able to manage a small number of concurrent connections.

I think a Siemens S7-1200 is limited to 7 concurrent connections and a Siemens LOGO can't do more than 3.

One alternative would be to open and close the connections all the time.
This however puts an unnecessary stress on the PLCs as for protocols like the S7 or the ADS protocol a handshake of multiple requests and responses has to be executed before being able to communicate.

As usually these services only require ad-hoc access to a PLC, it would be ideal to share connections between services.

Another problem occurs when you open a connection and keep it open for a prolonged time period.
Here it can happen quite often that a connection is terminated because the PLC has been turned off.

Per default the PLC connection has no means of automatically re-connecting.

The `PooledPlcDriverManager` can help you with both of these scenarios.

=== The PooledPlcDriverManager

The `PooledPlcDriverManager` is a wrapper around the normal `PlcDriverManager`.

The main difference is that as soon as a connection is requested, it will look if one already exists and return that.

If no connection exists it will create a new one and keep it in the pool.

There are no API differences from using the normal `PlcDriverManager` so you call `createConnection` and `close` just like with the normal PLC4X API.

The structure of the code is now more or less like if you would create a new connection for every request and close it afterwards.

Another benefit of the `PooledPlcDriverManager` is that it will check a connection for any problems before returning it to the client.

So if a connection was terminated, it will detect this and create a new connection.

=== Example

Here comes a little example program utilizing the `PooledPlcDriverManager`:

[source,java]
----
    PlcDriverManager driverManager = new PooledPlcDriverManager();

    // This just simulates a scenario where a lot of connections would be created and immediately destroyed again.
    for(int i = 0; i < 100; i++) {
        try(PlcConnection connection = driverManager.getConnection("...")) {

            ... do something ... (please refer to the PLC4J getting started for details)

        }
    }
----

NOTE: When sharing connections between multiple services, be sure to share the instance of the `PooledPldDriverManager` as otherwise you will result in having multiple pools.

=== The CachedDriverManager

There's an another version of pool manager with similar target but different implementation. 

The idea behind this second pool driver is that a connection could be lost for a lot of external reason without the possibility to handle those from the plc4x point of view (e.g. the cable is unplugged in a reading session). In the Cached Pool Manager every connection could be used for only a limited period of time, at the end the connection is no more valid and must be returned to the poll. 

Even in the Cached Pool Manager, like before, getting a connection from the pool is effortless so the typical live cycle of a connection is: 

```
Get a connection -> use the connection -> return the connection to the pool
```

In the Cached Pool Manager a watchdog will invalidate any open connection at the end of it's live time even if no answer came back from the PLC; in this case the library could continue to talk to the PLC with some other connections fetched from the pool. 

Let explain this concept in more detail using the Cached Pool with a modified version of the previous example:

[source,java]
----
    public static void main(String[] args) throws Exception {
        String connectionString = "s7://192.168.1.192";
            PlcDriverManager manager = new PlcDriverManager();
            PlcDriverManager cached = new CachedDriverManager(connectionString,() -> manager.getConnection(connectionString));
            for (int i = 0; i < 10000; i++) {
                try {
                    TimeUnit.MILLISECONDS.sleep(500);
                    try (PlcConnection conn = cached.getConnection(connectionString)) {
                        if (conn.isConnected()){
                            PlcReadRequest.Builder builder = conn.readRequestBuilder();
                            builder.addItem("PollingValue", "%DB1:4.0:BOOL");
                            PlcReadRequest readRequest = builder.build();
                            PlcReadResponse syncResponse = readRequest.execute().get(2000, TimeUnit.MILLISECONDS);
                            printResponse(syncResponse);
                        } else {
                            logger.info("PLC is not connected, let's try again to connect");
                            conn.connect();
                        }
                    }
                } catch (PlcConnectionException e){
                    logger.error("Connection exception in trying to connect", e);
                } catch (CancellationException  e){
                    logger.error("Polling Thread canceled", e);
                } catch (IllegalStateException e){
                    logger.error("Error in Netty state machine", e);
                } catch (ExecutionException e){
                    logger.error("Interrupted Exception fired", e);
                } catch (TimeoutException e) {
                    logger.error("Timeout exception fired", e);
                }
            }
        System.exit(0);
    }
----

In this snippet of code there are some considerations that are worth to be underlined.

* The `try-with-resources` statement (i.e. ``try (PlcConnection conn = cached.getConnection(connectionString))``) ensure that an open connection will be automatically closed and returned to the pool after the use. As said before if the connection get stuck for any reason, after a fixed amount of time will be killed by a software watchdog (i.e. the amount of time is now fixed to 5000 ms, will be configurable in the future);
* Check if the PLC is connected before reading some data is always advisable (i.e. ``conn.isConnected()``) but this doesn't mean that the PLC will be ready to answer to the connection, it means that the initial handshake went good and plc4x has the needed information to talk with the PLC;
* the use of `get()` must be done with a timeout (i.e. ``readRequest.execute().get(2000, TimeUnit.MILLISECONDS)``). After the timeout amount of time a `TimeoutException` will be fired. In the code this is trapped and signaled with a simple line of log. This case could happen because the PLC for some reason could decide to not answer or the physical connection could have some problem;
* the `PlcConnectionException` is a connection error that could happen in the handshaking phase between the PLC4x library and the PLC. It's a generic error;
* the `IllegalStateException` is a Netty library exception which could happen in some really troubled connection, mostly if a physical disconnection happen.

All the others exceptions (i.e. `ExecutionException` and `CancellationException`) are thread java related exceptions; in this example these are caught to show how plc4x could be used to handle all the external problems that could happen in talking to a PLC and could recover from them.