//
//  Licensed to the Apache Software Foundation (ASF) under one or more
//  contributor license agreements.  See the NOTICE file distributed with
//  this work for additional information regarding copyright ownership.
//  The ASF licenses this file to You under the Apache License, Version 2.0
//  (the "License"); you may not use this file except in compliance with
//  the License.  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
:imagesdir: ../img/

== Contributing

=== Branching model

The PLC4X project uses the following branching model.

The same model is used for a wide variety of other projects, so it should be pretty straight forward.

- `master` contains the latest released state.
- Development is performed on the `develop` branch.
- Features are developed in Feature-Branches with a prefix `feature/`
- Each minor release has a corresponding release branch `rel/{major-version}.{minor-version}`
- A release branch is spawned from `develop` only
- Bugfix releases don't have a dedicated release branch, they are just performed on the corresponding minor versions release branch

// Use http://www.webgraphviz.com/ for online editiing this ...
[graphviz, plc4x-branching-model, png]
----
digraph g{
    rankdir="LR";
    pad=0.5;
    nodesep=0.6;
    ranksep=0.5;
    forcelabels=true;

    node [fixedsize=true,
        shape=circle, style=empty, color="#909090", height=0.5
        fontcolor="deepskyblue", font="Arial bold", fontsize="14pt" ];
    edge [color="#909090", penwidth=3];

    node  [group="master"];
    m1    [label="master", width=0.9];
    m2   [label="0.2.0", width=0.9];
    m3   [label="0.2.1", width=0.9];
    m4   [label="", shape=circle, color="#b0b0b0"];
    m1 -> m2 -> m3
    m3 -> m4 [color="#b0b0b0", style=dashed];

    node  [group="rel/0.1", Ylabel="hurz"];
    r11   [label="rel/0.1", width=2, shape=box];
    r12   [label="0.1.0-SNAPSHOT", width=2, shape=box];
    r13   [label="0.1.0", width=0.9];
    r14   [label="0.1.1-SNAPSHOT", width=2, shape=box];
    r15   [label="", shape=circle, color="#b0b0b0"];
    r11 -> r12 -> r13 -> r14;
    r14 -> r15 [color="#b0b0b0", style=dashed];
    r13 -> m1

    node  [group="rel/0.2", Ylabel="hurz"];
    r21   [label="rel/0.2", width=2, shape=box];
    r22   [label="0.2.0-SNAPSHOT", width=2, shape=box];
    r23   [label="0.2.0", width=0.9];
    r24   [label="0.2.1-SNAPSHOT", width=2, shape=box];
    r25   [label="0.2.1", width=0.9];
    r26   [label="0.2.2-SNAPSHOT", width=2, shape=box];
    r27   [label="", shape=circle, color="#b0b0b0"];
    r21 -> r22 -> r23 -> r24 -> r25 -> r26;
    r26 -> r27 [color="#b0b0b0", style=dashed];
    r23 -> m2
    r25 -> m3

    node  [group="develop"];
    d1    [label="develop", width=2, shape=box];
    d2    [label="0.1.0-SNAPSHOT", width=2, shape=box];
    d3    [label="0.1.0-SNAPSHOT", width=2, shape=box];
    d4    [label="0.2.0-SNAPSHOT", width=2, shape=box];
    d5    [label="0.2.0-SNAPSHOT", width=2, shape=box];
    d6    [label="0.2.0-SNAPSHOT", width=2, shape=box];
    d7    [label="0.3.0-SNAPSHOT", width=2, shape=box];
    d8    [label="0.3.0-SNAPSHOT", width=2, shape=box];
    d9    [label="0.3.0-SNAPSHOT", width=2, shape=box];
    d10    [label="", shape=circle, color="#b0b0b0"];
    d1 -> d2 -> d3 -> d4 -> d5 -> d6 -> d7 -> d8 -> d9;
    d9 -> d10 [color="#b0b0b0", style=dashed];

    d3 -> r11
    d6 -> r21
}
----


