//
//  Licensed to the Apache Software Foundation (ASF) under one or more
//  contributor license agreements.  See the NOTICE file distributed with
//  this work for additional information regarding copyright ownership.
//  The ASF licenses this file to You under the Apache License, Version 2.0
//  (the "License"); you may not use this file except in compliance with
//  the License.  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

== InfluxDB Example

Note: This example only works with InfluxDB 2.0 and above, it will not work with InfluxDB 1.x.

Ideally you will setup an instance of InfluxDB 2.0 and create a `company` as well as a `bucket` and configure these in the `example.properties` file, or a copy of it.
Here you should also configure the name you want to give your `measurement` inside the `bucket` you just defined.

You should also adjust the PLC4X settings for connecting to the PLC datasource.

=== Running

First be sure the module is built:

    mvn package

Then you can run the application with the following command:

    java -jar target/plc4j-hello-influx-data-collection-0.7.0-SNAPSHOT-uber-jar.jar examples.properties

