//
//  Licensed to the Apache Software Foundation (ASF) under one or more
//  contributor license agreements.  See the NOTICE file distributed with
//  this work for additional information regarding copyright ownership.
//  The ASF licenses this file to You under the Apache License, Version 2.0
//  (the "License"); you may not use this file except in compliance with
//  the License.  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

== Introduction

The Plc4x OPC UA server integration is an Eclipse Milo OPC UA server that is able to use
Plc4x drivers to communicate.


== Building the server

The OPC UA server can be built using maven as part of the Plc4x build by using the with-opcua-server switch.

mvn install -P with-sandbox,with-opcua-server


== Running

Once the OPC UA server is running you are able to connect to it from your favorite OPC UA client using the connection string

opc.tcp://{ip.address}:12687/plc4x

Replacing the {ip.address} with the servers IP address.

== Configuration File

The config.yml file is used to configure the server.

version: The version is just an check to confirm that the right version of the configuration file is being used.

dir: Before using it the `dir` that is used to store the security certificates should be defined.

name:- This is the name of the OPC UA server. It can be anything but shouldn't contain spaces.

tcpPort: this can be used to change the opc.tcp port that is used.

httpPort: this can be used to change the http.tcp port that is used.

devices: is a list of PLC's or devices that the server should communicate with. Each device should included a name:, connectionString:, and a list of tags:.

  name: This is the name of the device. It can anything as long as it doesn't contain spaces.
  connectionString: Can be any valid Plc4x connection string.

For each tag the alias: and address: should be defined.

    alias: This is the name of tag it can be anything but shouldn't have spaces.

    address: This is any valid Plc4x address.

An example configuration file is shown below.

version: 0.1
dir: {security.directory}
name: Plc4x.OPC.UA.Server
tcpPort: 12687
httpPort: 8445
devices:
      - name: ModbusDevice
        connectionString: modbus://127.0.0.1:5467
        tags:
            -   alias: TemporaryREAL1
                address: 400001:REAL
            -   alias: TemporaryWORD2
                address: 400002:WORD
            -   alias: TemporaryUINT3
                address: 400003:UINT
            -   alias: TemporaryINT4
                address: 400004:INT
            -   alias: TemporaryREAL5
                address: 400005:REAL
            -   alias: TemporaryREAL6
                address: 400006:REAL
            -   alias: TemporaryREAL7
                address: 400007:REAL
            -   alias: TemporaryREAL8
                address: 400008:REAL
