//
//  Licensed to the Apache Software Foundation (ASF) under one or more
//  contributor license agreements.  See the NOTICE file distributed with
//  this work for additional information regarding copyright ownership.
//  The ASF licenses this file to You under the Apache License, Version 2.0
//  (the "License"); you may not use this file except in compliance with
//  the License.  You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

== Allen-Bradley Ethernet

The Allen-Bradley Ethernet protocol encapsulates a DF1 protocol body to transfer data. The PLC4X driver currently only
supports the protected typed logical read with a limited number of data types.

=== Connection

The connection string looks as follows: `ab-eth://<ip-address>/<station>`

The field address: `N<file>:<offset></bitnumber>:<datatype>[<numberofbytes>]`. The following data types are available
at the moment: SINBLEBIT (requires bitnumber to be set), WORD (2 byte integer), DWORD (4 byte integer), INTEGER (returns
the number of bytes requested as an array, for other data types <numberofbytes> will be ignored).

Example of a SINGLEBIT read: `N10:22/5:SINGLEBIT` (file 10, offset 22, bitnumber 5)

Example of a WORD read: `N10:84:WORD` (file 10, offset 84, 2 byte integer)