<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.apache.plc4x</groupId>
    <artifactId>plc4j-spi</artifactId>
    <version>0.14.0-SNAPSHOT</version>
  </parent>

  <artifactId>plc4j-spi-fields</artifactId>

  <name>PLC4J: SPI: Fields</name>

  <properties>
    <project.build.outputTimestamp>2024-02-16T14:53:02Z</project.build.outputTimestamp>
  </properties>

  <dependencies>
    <!-- PLC4J API -->
    <dependency>
      <groupId>org.apache.plc4x</groupId>
      <artifactId>plc4j-api</artifactId>
      <version>0.14.0-SNAPSHOT</version>
    </dependency>

    <!-- Import the read and write buffers used in the fields -->
    <dependency>
      <groupId>org.apache.plc4x</groupId>
      <artifactId>plc4j-spi-buffers-api</artifactId>
      <version>0.14.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.apache.plc4x</groupId>
      <artifactId>plc4j-spi-utils</artifactId>
      <version>0.14.0-SNAPSHOT</version>
    </dependency>

    <!-- Logging -->
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>

    <dependency>
      <groupId>org.apache.plc4x</groupId>
      <artifactId>plc4j-spi-values</artifactId>
      <version>0.14.0-SNAPSHOT</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

</project>
