//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//

// Code generated from the mspec by plc4net-code-gen. DO NOT EDIT.

namespace org.apache.plc4net.drivers.s7.readwrite.model
{
    public enum TransportSize : byte
    {
        BOOL = 0x01,
        BYTE = 0x02,
        WORD = 0x03,
        DWORD = 0x04,
        LWORD = 0x05,
        INT = 0x06,
        UINT = 0x07,
        SINT = 0x08,
        USINT = 0x09,
        DINT = 0x0A,
        UDINT = 0x0B,
        LINT = 0x0C,
        ULINT = 0x0D,
        COUNTER = 0x1C,
        REAL = 0x0E,
        LREAL = 0x0F,
        CHAR = 0x10,
        WCHAR = 0x11,
        STRING = 0x12,
        WSTRING = 0x13,
        S5TIME = 0x14,
        TIME = 0x15,
        LTIME = 0x16,
        DATE = 0x17,
        TIME_OF_DAY = 0x18,
        TOD = 0x19,
        LTIME_OF_DAY = 0x1A,
        LTOD = 0x1B,
        DATE_AND_TIME = 0x1C,
        DT = 0x1D,
        DATE_AND_LTIME = 0x1E,
        LDT = 0x1F,
        DTL = 0x21,
    }

    public static class TransportSizeExtensions
    {
        public static byte GetCode(this TransportSize value) => value switch
        {
            TransportSize.BOOL => 0x01,
            TransportSize.BYTE => 0x02,
            TransportSize.WORD => 0x04,
            TransportSize.DWORD => 0x06,
            TransportSize.LWORD => 0x00,
            TransportSize.INT => 0x05,
            TransportSize.UINT => 0x05,
            TransportSize.SINT => 0x02,
            TransportSize.USINT => 0x02,
            TransportSize.DINT => 0x07,
            TransportSize.UDINT => 0x07,
            TransportSize.LINT => 0x00,
            TransportSize.ULINT => 0x00,
            TransportSize.COUNTER => 0x1C,
            TransportSize.REAL => 0x08,
            TransportSize.LREAL => 0x00,
            TransportSize.CHAR => 0x03,
            TransportSize.WCHAR => 0x13,
            TransportSize.STRING => 0x03,
            TransportSize.WSTRING => 0x00,
            TransportSize.S5TIME => 0x00,
            TransportSize.TIME => 0x00,
            TransportSize.LTIME => 0x00,
            TransportSize.DATE => 0x00,
            TransportSize.TIME_OF_DAY => 0x00,
            TransportSize.TOD => 0x0A,
            TransportSize.LTIME_OF_DAY => 0x00,
            TransportSize.LTOD => 0x00,
            TransportSize.DT => 0x00,
            TransportSize.DATE_AND_LTIME => 0x00,
            TransportSize.LDT => 0x00,
            TransportSize.DTL => 0x00,
            _ => default,
        };
        public static byte GetShortName(this TransportSize value) => value switch
        {
            TransportSize.BOOL => (byte) 'X',
            TransportSize.BYTE => (byte) 'B',
            TransportSize.WORD => (byte) 'W',
            TransportSize.DWORD => (byte) 'D',
            TransportSize.LWORD => (byte) 'X',
            TransportSize.INT => (byte) 'W',
            TransportSize.UINT => (byte) 'W',
            TransportSize.SINT => (byte) 'B',
            TransportSize.USINT => (byte) 'B',
            TransportSize.DINT => (byte) 'D',
            TransportSize.UDINT => (byte) 'D',
            TransportSize.LINT => (byte) 'X',
            TransportSize.ULINT => (byte) 'X',
            TransportSize.COUNTER => (byte) 'X',
            TransportSize.REAL => (byte) 'D',
            TransportSize.LREAL => (byte) 'X',
            TransportSize.CHAR => (byte) 'B',
            TransportSize.WCHAR => (byte) 'X',
            TransportSize.STRING => (byte) 'X',
            TransportSize.WSTRING => (byte) 'X',
            TransportSize.S5TIME => (byte) 'X',
            TransportSize.TIME => (byte) 'X',
            TransportSize.LTIME => (byte) 'X',
            TransportSize.DATE => (byte) 'X',
            TransportSize.TIME_OF_DAY => (byte) 'X',
            TransportSize.TOD => (byte) 'X',
            TransportSize.LTIME_OF_DAY => (byte) 'X',
            TransportSize.LTOD => (byte) 'X',
            TransportSize.DT => (byte) 'X',
            TransportSize.DATE_AND_LTIME => (byte) 'X',
            TransportSize.LDT => (byte) 'X',
            TransportSize.DTL => (byte) 'X',
            _ => default,
        };
        public static byte GetSizeInBytes(this TransportSize value) => value switch
        {
            TransportSize.BOOL => 1,
            TransportSize.BYTE => 1,
            TransportSize.WORD => 2,
            TransportSize.DWORD => 4,
            TransportSize.LWORD => 8,
            TransportSize.INT => 2,
            TransportSize.UINT => 2,
            TransportSize.SINT => 1,
            TransportSize.USINT => 1,
            TransportSize.DINT => 4,
            TransportSize.UDINT => 4,
            TransportSize.LINT => 8,
            TransportSize.ULINT => 8,
            TransportSize.COUNTER => 2,
            TransportSize.REAL => 4,
            TransportSize.LREAL => 8,
            TransportSize.CHAR => 1,
            TransportSize.WCHAR => 2,
            TransportSize.STRING => 1,
            TransportSize.WSTRING => 2,
            TransportSize.S5TIME => 2,
            TransportSize.TIME => 4,
            TransportSize.LTIME => 8,
            TransportSize.DATE => 2,
            TransportSize.TIME_OF_DAY => 4,
            TransportSize.TOD => 4,
            TransportSize.LTIME_OF_DAY => 8,
            TransportSize.LTOD => 8,
            TransportSize.DT => 8,
            TransportSize.DATE_AND_LTIME => 8,
            TransportSize.LDT => 8,
            TransportSize.DTL => 12,
            _ => default,
        };
        public static TransportSize? GetBaseType(this TransportSize value) => value switch
        {
            TransportSize.BOOL => null,
            TransportSize.BYTE => null,
            TransportSize.WORD => null,
            TransportSize.DWORD => TransportSize.WORD,
            TransportSize.LWORD => null,
            TransportSize.INT => null,
            TransportSize.UINT => TransportSize.INT,
            TransportSize.SINT => TransportSize.INT,
            TransportSize.USINT => TransportSize.INT,
            TransportSize.DINT => TransportSize.INT,
            TransportSize.UDINT => TransportSize.INT,
            TransportSize.LINT => TransportSize.INT,
            TransportSize.ULINT => TransportSize.INT,
            TransportSize.COUNTER => null,
            TransportSize.REAL => null,
            TransportSize.LREAL => TransportSize.REAL,
            TransportSize.CHAR => null,
            TransportSize.WCHAR => null,
            TransportSize.STRING => null,
            TransportSize.WSTRING => null,
            TransportSize.S5TIME => null,
            TransportSize.TIME => null,
            TransportSize.LTIME => TransportSize.TIME,
            TransportSize.DATE => null,
            TransportSize.TIME_OF_DAY => null,
            TransportSize.TOD => null,
            TransportSize.LTIME_OF_DAY => null,
            TransportSize.LTOD => null,
            TransportSize.DT => null,
            TransportSize.DATE_AND_LTIME => null,
            TransportSize.LDT => null,
            TransportSize.DTL => null,
            _ => default,
        };
        public static DataTransportSize GetDataTransportSize(this TransportSize value) => value switch
        {
            TransportSize.BOOL => DataTransportSize.BIT,
            TransportSize.BYTE => DataTransportSize.BYTE_WORD_DWORD,
            TransportSize.WORD => DataTransportSize.BYTE_WORD_DWORD,
            TransportSize.DWORD => DataTransportSize.BYTE_WORD_DWORD,
            TransportSize.LWORD => DataTransportSize.BYTE_WORD_DWORD,
            TransportSize.INT => DataTransportSize.INTEGER,
            TransportSize.UINT => DataTransportSize.INTEGER,
            TransportSize.SINT => DataTransportSize.BYTE_WORD_DWORD,
            TransportSize.USINT => DataTransportSize.BYTE_WORD_DWORD,
            TransportSize.DINT => DataTransportSize.INTEGER,
            TransportSize.UDINT => DataTransportSize.INTEGER,
            TransportSize.LINT => DataTransportSize.BYTE_WORD_DWORD,
            TransportSize.ULINT => DataTransportSize.BYTE_WORD_DWORD,
            TransportSize.COUNTER => DataTransportSize.OCTET_STRING,
            TransportSize.REAL => DataTransportSize.REAL,
            TransportSize.LREAL => DataTransportSize.BYTE_WORD_DWORD,
            TransportSize.CHAR => DataTransportSize.OCTET_STRING,
            TransportSize.WCHAR => DataTransportSize.OCTET_STRING,
            TransportSize.STRING => DataTransportSize.OCTET_STRING,
            TransportSize.WSTRING => DataTransportSize.OCTET_STRING,
            TransportSize.S5TIME => DataTransportSize.BYTE_WORD_DWORD,
            TransportSize.TIME => DataTransportSize.BYTE_WORD_DWORD,
            TransportSize.LTIME => DataTransportSize.BYTE_WORD_DWORD,
            TransportSize.DATE => DataTransportSize.BYTE_WORD_DWORD,
            TransportSize.TIME_OF_DAY => DataTransportSize.BYTE_WORD_DWORD,
            TransportSize.TOD => DataTransportSize.BYTE_WORD_DWORD,
            TransportSize.LTIME_OF_DAY => DataTransportSize.BYTE_WORD_DWORD,
            TransportSize.LTOD => DataTransportSize.BYTE_WORD_DWORD,
            TransportSize.DT => DataTransportSize.BYTE_WORD_DWORD,
            TransportSize.DATE_AND_LTIME => DataTransportSize.BYTE_WORD_DWORD,
            TransportSize.LDT => DataTransportSize.BYTE_WORD_DWORD,
            TransportSize.DTL => DataTransportSize.BYTE_WORD_DWORD,
            _ => default,
        };
        public static string GetDataProtocolId(this TransportSize value) => value switch
        {
            TransportSize.BOOL => "IEC61131_BOOL",
            TransportSize.BYTE => "IEC61131_BYTE",
            TransportSize.WORD => "IEC61131_WORD",
            TransportSize.DWORD => "IEC61131_DWORD",
            TransportSize.LWORD => "IEC61131_LWORD",
            TransportSize.INT => "IEC61131_INT",
            TransportSize.UINT => "IEC61131_UINT",
            TransportSize.SINT => "IEC61131_SINT",
            TransportSize.USINT => "IEC61131_USINT",
            TransportSize.DINT => "IEC61131_DINT",
            TransportSize.UDINT => "IEC61131_UDINT",
            TransportSize.LINT => "IEC61131_LINT",
            TransportSize.ULINT => "IEC61131_ULINT",
            TransportSize.COUNTER => "IEC61131_INT",
            TransportSize.REAL => "IEC61131_REAL",
            TransportSize.LREAL => "IEC61131_LREAL",
            TransportSize.CHAR => "IEC61131_CHAR",
            TransportSize.WCHAR => "IEC61131_WCHAR",
            TransportSize.STRING => "IEC61131_STRING",
            TransportSize.WSTRING => "IEC61131_WSTRING",
            TransportSize.S5TIME => "S7_S5TIME",
            TransportSize.TIME => "IEC61131_TIME",
            TransportSize.LTIME => "IEC61131_LTIME",
            TransportSize.DATE => "IEC61131_DATE",
            TransportSize.TIME_OF_DAY => "IEC61131_TIME_OF_DAY",
            TransportSize.TOD => "IEC61131_TIME_OF_DAY",
            TransportSize.LTIME_OF_DAY => "IEC61131_LTIME_OF_DAY",
            TransportSize.LTOD => "IEC61131_LTIME_OF_DAY",
            TransportSize.DT => "IEC61131_DATE_AND_TIME",
            TransportSize.DATE_AND_LTIME => "IEC61131_DATE_AND_LTIME",
            TransportSize.LDT => "IEC61131_DATE_AND_LTIME",
            TransportSize.DTL => "IEC61131_DTL",
            _ => default,
        };
        public static bool GetSupported_S7_300(this TransportSize value) => value switch
        {
            TransportSize.BOOL => true,
            TransportSize.BYTE => true,
            TransportSize.WORD => true,
            TransportSize.DWORD => true,
            TransportSize.LWORD => false,
            TransportSize.INT => true,
            TransportSize.UINT => false,
            TransportSize.SINT => false,
            TransportSize.USINT => false,
            TransportSize.DINT => true,
            TransportSize.UDINT => false,
            TransportSize.LINT => false,
            TransportSize.ULINT => false,
            TransportSize.COUNTER => true,
            TransportSize.REAL => true,
            TransportSize.LREAL => false,
            TransportSize.CHAR => true,
            TransportSize.WCHAR => false,
            TransportSize.STRING => true,
            TransportSize.WSTRING => false,
            TransportSize.S5TIME => true,
            TransportSize.TIME => true,
            TransportSize.LTIME => false,
            TransportSize.DATE => true,
            TransportSize.TIME_OF_DAY => true,
            TransportSize.TOD => true,
            TransportSize.LTIME_OF_DAY => false,
            TransportSize.LTOD => false,
            TransportSize.DT => true,
            TransportSize.DATE_AND_LTIME => false,
            TransportSize.LDT => false,
            TransportSize.DTL => false,
            _ => default,
        };
        public static bool GetSupported_S7_400(this TransportSize value) => value switch
        {
            TransportSize.BOOL => true,
            TransportSize.BYTE => true,
            TransportSize.WORD => true,
            TransportSize.DWORD => true,
            TransportSize.LWORD => false,
            TransportSize.INT => true,
            TransportSize.UINT => false,
            TransportSize.SINT => false,
            TransportSize.USINT => false,
            TransportSize.DINT => true,
            TransportSize.UDINT => false,
            TransportSize.LINT => false,
            TransportSize.ULINT => false,
            TransportSize.COUNTER => true,
            TransportSize.REAL => true,
            TransportSize.LREAL => false,
            TransportSize.CHAR => true,
            TransportSize.WCHAR => false,
            TransportSize.STRING => true,
            TransportSize.WSTRING => false,
            TransportSize.S5TIME => true,
            TransportSize.TIME => true,
            TransportSize.LTIME => false,
            TransportSize.DATE => true,
            TransportSize.TIME_OF_DAY => true,
            TransportSize.TOD => true,
            TransportSize.LTIME_OF_DAY => false,
            TransportSize.LTOD => false,
            TransportSize.DT => true,
            TransportSize.DATE_AND_LTIME => false,
            TransportSize.LDT => false,
            TransportSize.DTL => false,
            _ => default,
        };
        public static bool GetSupported_S7_1200(this TransportSize value) => value switch
        {
            TransportSize.BOOL => true,
            TransportSize.BYTE => true,
            TransportSize.WORD => true,
            TransportSize.DWORD => true,
            TransportSize.LWORD => false,
            TransportSize.INT => true,
            TransportSize.UINT => true,
            TransportSize.SINT => true,
            TransportSize.USINT => true,
            TransportSize.DINT => true,
            TransportSize.UDINT => true,
            TransportSize.LINT => false,
            TransportSize.ULINT => false,
            TransportSize.COUNTER => true,
            TransportSize.REAL => true,
            TransportSize.LREAL => true,
            TransportSize.CHAR => true,
            TransportSize.WCHAR => true,
            TransportSize.STRING => true,
            TransportSize.WSTRING => true,
            TransportSize.S5TIME => false,
            TransportSize.TIME => true,
            TransportSize.LTIME => false,
            TransportSize.DATE => true,
            TransportSize.TIME_OF_DAY => true,
            TransportSize.TOD => true,
            TransportSize.LTIME_OF_DAY => false,
            TransportSize.LTOD => false,
            TransportSize.DT => false,
            TransportSize.DATE_AND_LTIME => false,
            TransportSize.LDT => false,
            TransportSize.DTL => true,
            _ => default,
        };
        public static bool GetSupported_S7_1500(this TransportSize value) => value switch
        {
            TransportSize.BOOL => true,
            TransportSize.BYTE => true,
            TransportSize.WORD => true,
            TransportSize.DWORD => true,
            TransportSize.LWORD => true,
            TransportSize.INT => true,
            TransportSize.UINT => true,
            TransportSize.SINT => true,
            TransportSize.USINT => true,
            TransportSize.DINT => true,
            TransportSize.UDINT => true,
            TransportSize.LINT => true,
            TransportSize.ULINT => true,
            TransportSize.COUNTER => true,
            TransportSize.REAL => true,
            TransportSize.LREAL => true,
            TransportSize.CHAR => true,
            TransportSize.WCHAR => true,
            TransportSize.STRING => true,
            TransportSize.WSTRING => true,
            TransportSize.S5TIME => true,
            TransportSize.TIME => true,
            TransportSize.LTIME => true,
            TransportSize.DATE => true,
            TransportSize.TIME_OF_DAY => true,
            TransportSize.TOD => true,
            TransportSize.LTIME_OF_DAY => true,
            TransportSize.LTOD => true,
            TransportSize.DT => true,
            TransportSize.DATE_AND_LTIME => true,
            TransportSize.LDT => true,
            TransportSize.DTL => true,
            _ => default,
        };
        public static bool GetSupported_LOGO(this TransportSize value) => value switch
        {
            TransportSize.BOOL => true,
            TransportSize.BYTE => true,
            TransportSize.WORD => true,
            TransportSize.DWORD => true,
            TransportSize.LWORD => false,
            TransportSize.INT => true,
            TransportSize.UINT => true,
            TransportSize.SINT => true,
            TransportSize.USINT => true,
            TransportSize.DINT => true,
            TransportSize.UDINT => true,
            TransportSize.LINT => false,
            TransportSize.ULINT => false,
            TransportSize.COUNTER => false,
            TransportSize.REAL => true,
            TransportSize.LREAL => false,
            TransportSize.CHAR => true,
            TransportSize.WCHAR => true,
            TransportSize.STRING => true,
            TransportSize.WSTRING => true,
            TransportSize.S5TIME => false,
            TransportSize.TIME => true,
            TransportSize.LTIME => false,
            TransportSize.DATE => true,
            TransportSize.TIME_OF_DAY => true,
            TransportSize.TOD => true,
            TransportSize.LTIME_OF_DAY => true,
            TransportSize.LTOD => true,
            TransportSize.DT => false,
            TransportSize.DATE_AND_LTIME => false,
            TransportSize.LDT => false,
            TransportSize.DTL => false,
            _ => default,
        };
        public static TransportSize FirstEnumForFieldCode(byte code) => code switch
        {
            0x01 => TransportSize.BOOL,
            0x02 => TransportSize.BYTE,
            0x04 => TransportSize.WORD,
            0x06 => TransportSize.DWORD,
            0x00 => TransportSize.LWORD,
            0x05 => TransportSize.INT,
            0x07 => TransportSize.DINT,
            0x1C => TransportSize.COUNTER,
            0x08 => TransportSize.REAL,
            0x03 => TransportSize.CHAR,
            0x13 => TransportSize.WCHAR,
            0x0A => TransportSize.TOD,
            _ => default,
        };
    }
}
